### ISSUE TITLE
bug: nested different types of `join` conflict with one another

### ISSUE THREAD

**Issue by Tronikelis** [saadeghi/daisyui#2912] opened 2024-03-16 14:28 UTC
### What version of daisyUI are you using?

4.7.2

### Which browsers are you seeing the problem on?

Chrome, Firefox

### Reproduction URL

https://play.tailwindcss.com/tRuVSiXFZv

### Describe your issue

Horizontally joined buttons' border radius inside vertically joined items conflict

![image](https://github.com/saadeghi/daisyui/assets/56039679/c37f782d-03bb-48ba-abc1-e2e081d09302)

```html
<div class="join join-vertical w-full">
  <div class="collapse join-item collapse-arrow border border-base-300">
    <input type="radio" name="my-accordion-4" checked="checked" />
    <div class="collapse-title text-xl font-medium">Click to open this one and close others</div>
    <div class="collapse-content">
      <p>hello</p>

      <div class="join join-horizontal">
        <button class="btn join-item">Button</button>
        <button class="btn join-item">Button</button>
        <button class="btn join-item">Button</button>
        <button class="btn join-item">Button</button>
        <button class="btn join-item">Button</button>
        <button class="btn join-item">Button</button>
      </div>
    </div>
  </div>
```

**Comment by saadeghi** [comment] 2024-03-18 11:32
duplicate of #2413

**Closed by saadeghi** 2024-03-18 11:32 UTC
