### ISSUE TITLE
bug: daisyui utils classes issues

### ISSUE THREAD

**Issue by raja-sultan-muslim-hands** [saadeghi/daisyui#3278] opened 2024-11-17 21:53 UTC
### What version of daisyUI are you using?

v4.12.14

### Which browsers are you seeing the problem on?

Chrome

### Reproduction URL

test

### Describe your issue

I am using daisyui 4.12.14 version with  tailwindcss v3.4.15 with next js 14 util classes are not working like md, lg, xl all these classes are not working why?

**Comment by saadeghi** [comment] 2024-11-17 21:55
Can you share a reproduction URL please?

**Comment by raja-sultan-muslim-hands** [comment] 2024-11-17 21:59
i dont have live url I am tetsing on live server issue is it taking only bg-green-500 for all the devices md:bg-red-500 is not working same for width and heights as well

![image](https://github.com/user-attachments/assets/b361766f-c5ee-40ed-8f7f-e3b3f3f8e57c)

this is my package json
{
  "name": "chatbot-agent-ai",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "prisma generate && next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@clerk/nextjs": "^5.3.3",
    "@dicebear/collection": "^9.0.1",
    "@dicebear/core": "^9.0.1",
    "@draft-js-plugins/editor": "^4.1.4",
    "@edgestore/react": "^0.2.2",
    "@edgestore/server": "^0.2.2",
    "@langchain/community": "^0.2.28",
    "@langchain/core": "^0.2.27",
    "@langchain/openai": "^0.2.7",
    "@langchain/pinecone": "^0.0.9",
    "@pinecone-database/pinecone": "^3.0.1",
    "@prisma/client": "^5.19.1",
    "@radix-ui/react-accordion": "^1.2.1",
    "@radix-ui/react-avatar": "^1.1.0",
    "@radix-ui/react-dialog": "^1.1.2",
    "@radix-ui/react-dropdown-menu": "^2.1.1",
    "@radix-ui/react-label": "^2.1.0",
    "@radix-ui/react-popover": "^1.1.2",
    "@radix-ui/react-progress": "^1.1.0",
    "@radix-ui/react-scroll-area": "^1.1.0",
    "@radix-ui/react-select": "^2.1.1",
    "@radix-ui/react-separator": "^1.1.0",
    "@radix-ui/react-slot": "^1.1.0",
    "@radix-ui/react-switch": "^1.1.0",
    "@radix-ui/react-tabs": "^1.1.0",
    "@radix-ui/react-toast": "^1.2.1",
    "@radix-ui/react-tooltip": "^1.1.3",
    "@react-google-maps/api": "^2.19.3",
    "@sparticuz/chromium": "^123.0.0",
    "@stripe/stripe-js": "^4.4.0",
    "@uiw/react-color": "^2.3.0",
    "autoprefixer": "^10.4.20",
    "axios": "^1.7.7",
    "canvg": "^4.0.2",
    "chart.js": "^4.4.4",
    "class-variance-authority": "^0.7.0",
    "clsx": "^2.1.1",
    "daisyui": "^4.12.14",
    "date-fns": "^3.6.0",
    "draft-js-export-html": "^1.4.1",
    "draftjs-to-html": "^0.9.1",
    "editorjs-html": "^3.4.3",
    "formidable": "^3.5.1",
    "fs": "^0.0.1-security",
    "html-to-text": "^9.0.5",
    "jspdf": "^2.5.2",
    "langchain": "^0.1.37",
    "lucide-react": "^0.408.0",
    "next": "14.2.5",
    "next-themes": "^0.3.0",
    "nodemailer": "^6.9.14",
    "openai": "^4.56.0",
    "pdf-parse": "^1.1.1",
    "puppeteer-core": "^22.6.2",
    "pusher": "^5.2.0",
    "pusher-js": "^8.4.0-rc2",
    "react": "^18",
    "react-chartjs-2": "^5.2.0",
    "react-day-picker": "^8.10.1",
    "react-dom": "^18",
    "react-dropzone": "^14.2.3",
    "react-markdown": "^9.0.1",
    "recharts": "^2.12.7",
    "remark-gfm": "^4.0.0",
    "sharp": "^0.33.5",
    "sonner": "^1.5.0",
    "stripe": "^16.10.0",
    "swr": "^2.2.5",
    "tailwind-merge": "^2.4.0",
    "tailwindcss-animate": "^1.0.7",
    "uninstall": "^0.0.0",
    "vercel": "^32.3.0",
    "zustand": "^4.5.4"
  },
  "devDependencies": {
    "@types/draft-js": "^0.11.18",
    "@types/draftjs-to-html": "^0.8.4",
    "@types/formidable": "^3.4.5",
    "@types/html-to-text": "^9.0.4",
    "@types/node": "^20",
    "@types/nodemailer": "^6.4.15",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "eslint": "^8",
    "eslint-config-next": "14.2.5",
    "postcss": "^8.4.49",
    "prisma": "^5.17.0",
    "tailwindcss": "^3.4.15",
    "typescript": "^5"
  }
}

**Comment by saadeghi** [comment] 2024-11-17 22:05
1. `bg-red-500` is not even from daisyUI. It's a Tailwind CSS color.
2. How can I help you debugging your code without seeing your code?

I have to close this because it's not an issue from daisyUI and it probably is not an issue of Tailwind either. Feel free to share a reproduction link and I would be happy to help.

**Closed by saadeghi** 2024-11-17 22:05 UTC
