### ISSUE TITLE
The style of select options is different from the main design

### ISSUE THREAD

**Issue by weicheng2138** [saadeghi/daisyui#649] opened 2022-03-25 06:07 UTC
I'm currious that the design of dropdown is great, but select is under the default options design. Why not make the design just as dropdown.

**Select**
![螢幕擷取畫面 2022-03-25 140119](https://user-images.githubusercontent.com/13548635/160063969-c0603409-a986-4bab-bad9-5e39fa3005a9.png)

**Dropdown**
![螢幕擷取畫面 2022-03-25 140543](https://user-images.githubusercontent.com/13548635/160064102-38e0bf3d-096a-42a1-a704-2012133b6419.png)

**Comment by saadeghi** [comment] 2022-03-25 11:16
duplicate of #357

**Closed by saadeghi** 2022-03-25 11:16 UTC

**Comment by saadeghi** [comment] 2022-03-25 11:17
`<select>` list can not be styled using CSS
