### ISSUE TITLE
Unwanted scroll while inputing to search box

### ISSUE THREAD

**Issue by tamagoez** [saadeghi/daisyui#875] opened 2022-06-19 15:10 UTC
When I focus to search box(click or `CTRL+k`) and input something, it automatically scroll.
I found this issue on Chrome(Windows).
Thank you.

**Comment by mvz** [comment] 2022-07-03 06:53
I have the same problem in Firefox on Linux. Also, cursor keys and page up/down don't work outside the search box. I can only scroll using the touch pad.

**Comment by CapitaineToinon** [comment] 2022-08-09 07:02
The unwanted scroll seems to be caused by bad css on the daisyui doc and can be fixed. However the arrow/page up keys not working is caused by [sveltekit setting up a tabindex="-1" on the body tag](https://github.com/sveltejs/kit/issues/3501). This issue was resolved in later versions but when I tried upgrading daisyui's doc site to the latest version of sveltekit, I had a bunch of css issues.

**Comment by saadeghi** [comment] 2022-08-09 16:51
I'm afraid removing `scroll-padding-top` is not worth it. ([reason](https://github.com/saadeghi/daisyui/pull/1008#issuecomment-1209627061))

**Comment by mvz** [comment] 2022-08-09 17:16
I would guess the unwanted scrolling is javascript related, so removing `scroll-padding-top` might stop the actual effect from happening, the cause is probably still there.

**Comment by CapitaineToinon** [comment] 2022-08-10 08:23
Ah yeah fair enough about `scroll-padding-top` but I don't believe it's javascript related. As far as I understand, the input is considered outside of the view because of the scroll padding and therefore makes the browser try to bring it in view whenever the input is focused or typed in. You can even see the jumps increase if you also increase the `scroll-padding-top` property. I tried replacing the `svelte-typehead` component by a simple `input` tag, disabled javascript and the problem still persist.

**Comment by saadeghi** [comment] 2022-08-10 08:38
@CapitaineToinon 
I agree.  
I don't have a proper solution for this right now. I will try to see if this  approach fixes the issue:  
Removing the `scroll-padding-top` while typing inside the search box and then add it again after search box loses focus 😬

**Comment by mvz** [comment] 2022-08-10 11:30
I was able to reproduce the scrolling problem with pure css:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
<style>
body {
  margin: 0;
}

.content {
  max-width: 40em;
  margin-left: 16px;
  margin-right: auto;

}
.sticky-header {
  position: sticky;
  top: 0;
  padding: 16px;
  background: white;
}
.drawer {
  overflow: hidden;
  height: 100dvh;
}
.drawer-content {
  scroll-behavior: smooth;
  scroll-padding-top: 5rem;
  height: inherit;
  overflow-y: auto;
}
.navbar {
  display: flex;
}
</style>
  </head>
  <body>
    <div class="drawer">
      <div class="drawer-content">
        <div class="sticky-header">
          <nav class="navbar">
            <div>Hello</div>
            <div><input type="text"/></div>
          </nav>
        </div>
        <div class="content">
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        </div>
      </div>
    </div>
  </body>
</html>
```

The important elements are the `overflow: hidden; height: 100dvh;` on the `.drawer` class, and `height: inherit; overflow: auto` on the `.drawer-content` class. Removing the overflow and height properties on those two elements also fixes the problem on the daisyui.com site.

**Closed** 2022-10-31 18:58 UTC
