### ISSUE TITLE
I don't know how to debug this error and get to the root of the issue

### ISSUE THREAD

**Issue by OdifYltsaeb** [saadeghi/daisyui#711] opened 2022-04-13 11:56 UTC
So when I start my nextjs project I get this error after updating the packages (tailwind, daisyui, nextjs)
```

yarn run v1.22.17
$ next dev -p 8000
ready - started server on 0.0.0.0:8000, url: http://localhost:8000
info  - Loaded env from /home/alan/projects/trackonomy/delta_next_dash/.env.development

warn - The `purge`/`content` options have changed in Tailwind CSS v3.0.
warn - Update your configuration file to eliminate this warning.
warn - https://tailwindcss.com/docs/upgrade-guide#configure-content-sources

🌼 daisyUI components 2.13.6  https://github.com/saadeghi/daisyui
  
  🌼 daisyUI components 2.13.6  https://github.com/saadeghi/daisyui
    
    🌼 daisyUI components 2.13.6  https://github.com/saadeghi/daisyui
      wait  - compiling...
      error - ./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[3].oneOf[5].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[3].oneOf[5].use[2]!./node_modules/next/dist/build/webpack/loaders/resolve-url-loader/index.js??ruleSet[1].rules[3].oneOf[5].use[3]!./node_modules/next/dist/compiled/sass-loader/cjs.js??ruleSet[1].rules[3].oneOf[5].use[4]!./styles/components/navbar.module.scss
      Error: Unable to parse color from string: 
          at Array.forEach (<anonymous>)
          at Array.forEach (<anonymous>)
          at Array.forEach (<anonymous>)
```
          
          
Is it even a daisyui problem? Or  problem with css-loader, postcss-loader or resolve-url-loader? Because my navbar.module.css has not changed and is still the same:

.navbar {
```
    @apply shadow-lg;

    nav {
        margin-left: 8rem;
        @apply flex flex-row flex-grow pr-7 items-center;

        > a {
            @apply text-lg uppercase font-bold pt-7 pr-4 pb-7 pl-4 relative leading-8;

            &:after {
                content: '';
                @apply border-b-4 border-solid border-accent;
                @apply w-0;
                @apply absolute bottom-0 right-0 left-0;
                @apply transition-all;
            }

            &.active {
                &:after {
                    @apply w-full;
                }
            }

            &.last {
                @apply pl-0 pr-0 ml-auto flex flex-row items-center;
            }
        }
    }
}
```

**Comment by OdifYltsaeb** [comment] 2022-04-13 13:40
There is one colour there - border-accent... I only posted it here because it prints daisyUI out thrice. But is it even this package's issue?

**Comment by ElliotGibson** [comment] 2022-04-13 14:44
How is the border-accent colour defined - based on the error message, originating from webpacks loader & via css-loader - I believe this is actually caused by the colour, not its usage - although it is difficult to tell based on the final part of the error message - I'd look at where you're declaring that colour & possible see if you can change that colour for a different one for now to see if that is the issue :) - if hls or rgb I am aware of an issue where this error was being thrown if you used **,** to delimit colour values, although I'm fairly sure this was removed (I think the initial error was due to the authors wanting to replicate the latest version of the spec :) )

**Comment by OdifYltsaeb** [comment] 2022-04-13 15:31
All the colours are defined in tailwind.config.js, which looks like this:

```
const daisyui = require('daisyui');

module.exports = {
    purge: ['./pages/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}'],
    important: true,
    variants: {
        extend: {
            backgroundColor: ['checked'],
            borderColor: ['checked'],
        },
    },
    plugins: [daisyui],
    theme: {
        colors: {
            white: "rgba(255, 255, 255, 1)",
            primary: {
                default: "rgba(0, 57, 107, 1)",
                light: "rgba(0, 57, 107, 0.6)",
                lighter: "rgba(0, 57, 107, 0.36)",
                lightest: "rgba(0, 57, 107, 0.12)",
            },
            accent: {
                default: "rgba(235, 113, 0, 1)",
                light: "rgba(235, 113, 0, 0.6)",
                lighter: "rgba(235, 113, 0, 0.36)",
                lightest: "rgba(235, 113, 0, 0.12)",
            },
            neutral: {
                default: "rgba(38, 50, 56, 1)",
                light: "rgba(38, 50, 56, 0.6)",
                lighter: "rgba(38, 50, 56, 0.36)",
                lightest: "rgba(38, 50, 56, 0.12)",
            },
            base: {
                default: "rgba(255, 255, 255, 1)",
                light: "rgba(255, 255, 255, 0.6)",
                lighter: "rgba(255, 255, 255, 0.36)",
                lightest: "rgba(255, 255, 255, 0.12)",
            },
            border: {
                default: "rgba(207, 216, 220, 1)",
                light: "rgba(207, 216, 220, 0.6)",
                lighter: "rgba(207, 216, 220, 0.36)",
                lightest: "rgba(207, 216, 220, 0.12)",
            },
            bg: {
                default: "rgba(236, 239, 241, 1)",
                light: "rgba(236, 239, 241, 0.6)",
                lighter: "rgba(236, 239, 241, 0.36)",
                lightest: "rgba(236, 239, 241, 0.12)",
            },
            info: {
                default: "rgba(0, 117, 219, 1)",
                light: "rgba(0, 117, 219, 0.6)",
                lighter: "rgba(0, 117, 219, 0.36)",
                lightest: "rgba(0, 117, 219, 0.12)",
            },
            success: {
                default: "rgba(5, 148, 79, 1)",
                light: "rgba(5, 148, 79, 0.6)",
                lighter: "rgba(5, 148, 79, 0.36)",
                lightest: "rgba(5, 148, 79, 0.12)",
            },
            warning: {
                default: "rgba(199, 133, 0, 1)",
                light: "rgba(199, 133, 0, 0.6)",
                lighter: "rgba(199, 133, 0, 0.36)",
                lightest: "rgba(199, 133, 0, 0.12)",
            },
            error: {
                default: "rgba(218, 44, 23, 1)",
                light: "rgba(218, 44, 23, 0.6)",
                lighter: "rgba(218, 44, 23, 0.36)",
                lightest: "rgba(218, 44, 23, 0.12)",
            },
            "decorative-1": {
                default: "rgba(235, 112, 146, 1)",
                light: "rgba(235, 112, 146, 0.6)",
                lighter: "rgba(235, 112, 146, 0.36)",
                lightest: "rgba(235, 112, 146, 0.12)",
            },
            "decorative-2": {
                default: "rgba(3, 180, 167, 1)",
                light: "rgba(3, 180, 167, 0.6)",
                lighter: "rgba(3, 180, 167, 0.36)",
                lightest: "rgba(3, 180, 167, 0.12)",
            },
            "decorative-3": {
                default: "rgba(209, 125, 254, 1)",
                light: "rgba(209, 125, 254, 0.6)",
                lighter: "rgba(209, 125, 254, 0.36)",
                lightest: "rgba(209, 125, 254, 0.12)",
            },
            "dark-primary": {
                default: "rgba(191, 238, 255, 0.96)",
                light: "rgba(191, 238, 255, 0.6)",
                lighter: "rgba(191, 238, 255, 0.36)",
                lightest: "rgba(191, 238, 255, 0.2)",
            },
            "dark-accent": {
                default: "rgba(255, 171, 92, 0.96)",
                light: "rgba(255, 171, 92, 0.6)",
                lighter: "rgba(255, 171, 92, 0.36)",
                lightest: "rgba(255, 171, 92, 0.20)",
            },
            "dark-neutral": {
                default: "rgba(255, 255, 255, 0.96)",
                light: "rgba(255, 255, 255, 0.6)",
                lighter: "rgba(255, 255, 255, 0.36)",
                lightest: "rgba(255, 255, 255, 0.20)",
            },
            "dark-base": {
                default: "rgba(38, 50, 56, 1)",
                light: "rgba(38, 50, 56, 0.6)",
                lighter: "rgba(38, 50, 56, 0.36)",
                lightest: "rgba(38, 50, 56, 0.2)",
            },
            "dark-border": {
                default: "rgba(236, 239, 241, 0.96)",
                light: "rgba(236, 239, 241, 0.6)",
                lighter: "rgba(236, 239, 241, 0.36)",
                lightest: "rgba(236, 239, 241, 0.20)",
            },
            "dark-bg": {
                default: "rgba(55, 71, 79, 0.96)",
                light: "rgba(55, 71, 79, 0.6)",
                lighter: "rgba(55, 71, 79, 0.36)",
                lightest: "rgba(55, 71, 79, 0.20)",
            },
            "dark-info": {
                default: "rgba(120, 199, 252, 0.96)",
                light: "rgba(120, 199, 252, 0.6)",
                lighter: "rgba(120, 199, 252, 0.36)",
                lightest: "rgba(120, 199, 252, 0.20)",
            },
            "dark-success": {
                default: "rgba(144, 223, 157, 0.96)",
                light: "rgba(144, 223, 157, 0.6)",
                lighter: "rgba(144, 223, 157, 0.36)",
                lightest: "rgba(144, 223, 157, 0.20)",
            },
            "dark-warning": {
                default: "rgba(244, 206, 123, 0.96)",
                light: "rgba(244, 206, 123, 0.6)",
                lighter: "rgba(244, 206, 123, 0.36)",
                lightest: "rgba(244, 206, 123, 0.20)",
            },
            "dark-error": {
                default: "rgba(221, 129, 126, 0.96)",
                light: "rgba(221, 129, 126, 0.6)",
                lighter: "rgba(221, 129, 126, 0.36)",
                lightest: "rgba(221, 129, 126, 0.20)",
            },
            "dark-decorative-1": {
                default: "rgba(235, 112, 146, 0.96)",
                light: "rgba(235, 112, 146, 0.6)",
                lighter: "rgba(235, 112, 146, 0.36)",
                lightest: "rgba(235, 112, 146, 0.12)",
            },
            "dark-decorative-2": {
                default: "rgba(158, 169, 241, 0.96)",
                light: "rgba(158, 169, 241, 0.6)",
                lighter: "rgba(158, 169, 241, 0.36)",
                lightest: "rgba(158, 169, 241, 0.20)",
            },
            "dark-decorative-3": {
                default: "rgba(151, 223, 216, 0.96)",
                light: "rgba(151, 223, 216, 0.6)",
                lighter: "rgba(151, 223, 216, 0.36)",
                lightest: "rgba(151, 223, 216, 0.20)",
            },
        },
        fontFamily: {
            header: ["Gotham"],
            body: ["Inter"],
        },
    },
    daisyui: {
        themes: [
            {
                light: {
                    "primary": "rgba(0, 57, 107, 1)",
                    "secondary": "",
                    "accent": "rgba(235, 113, 0, 1)",
                    "neutral": "rgba(38, 50, 56, 1)",
                    "base-100": "rgba(255, 255, 255, 1)",
                    "info": "rgba(0, 117, 219, 1)",
                    "success": "rgba(5, 148, 79, 1)",
                    "warning": "rgba(199, 133, 0, 1)",
                    "error": "rgba(218, 44, 23, 1)",
                },
                dark: {
                    "primary": "rgba(191, 238, 255, 0.96)",
                    "secondary": "",
                    "accent": "rgba(255, 171, 92, 0.96)",
                    "neutral": "rgba(255, 255, 255, 0.96)",
                    "base-100": "rgba(38, 50, 56, 1)",
                    "info": "rgba(120, 199, 252, 0.96)",
                    "success": "rgba(144, 223, 157, 0.96)",
                    "warning": "rgba(244, 206, 123, 0.96)",
                    "error": "rgba(221, 129, 126, 0.96)",
                },
            },
        ],
    },
};

```

But I think I just figured out what the problem was. There were two colours defined in daisyui settings, which were defined as empty strings. And I guess those were the ones causing the problem ( see secondary colour in the above config file.

@saadeghi I'm not sure if this is a bug, though. As "Please don't configure empty strings as colours in settings" pretty much fixes it.

But the official issue description is:
If colour is configured as empty string the compilation process fails.

**Comment by saadeghi** [comment] 2022-04-13 15:44
That makes sense... an empty string is not a valid color value of course.  
And all the `required` colors in [this table](https://daisyui.com/docs/colors/) should be defined (including `secondary`)

I guess we can close this issue now

**Closed by saadeghi** 2022-04-13 15:44 UTC
