### ISSUE TITLE
Order of classes is wrong, using SvelteKit/Vite + WindiCSS

### ISSUE THREAD

**Issue by AlexanderReiswich** [saadeghi/daisyui#83] opened 2021-06-14 22:34 UTC
Sample repo: https://github.com/AlexanderReiswich/windi-daisy-test

When I add the CDN script everything works fine, but when added as a plugin the order of classes gets messed up. For example:

```css
/* windicss layer components */
.btn-sm {
  ...
}

...other classes...

.btn {
  ...
}
```

So the main .btn class is loaded after the modifying class, and as a result, when an element has the class "btn btn-sm" the properties of .btn-sm get partially overwritten.

This is probably caused by how WindiCSS generates the styles, unless I'm missing something.

**Comment by saadeghi** [comment] 2021-06-15 20:19
@AlexanderReiswich Thanks for the sample repo.  
I made another [sample repo](https://github.com/saadeghi/windi-vs-tailwind-daisyui-class-order-issue) and now I can confirm this is because how Windi generates styles.  
I'm closing this issue because there's nothing I can do on my end but I created an issue on WindiCSS to follow up:  
[**Incorrect CSS order for plugin components and utilities**](https://github.com/windicss/windicss/issues/345)

**Closed by saadeghi** 2021-06-15 20:19 UTC
Labels: bug, in progress
