### ISSUE TITLE
Button primary with type == 'submit' renders as outline

### ISSUE THREAD

**Issue by Afani97** [saadeghi/daisyui#1418] opened 2022-12-06 21:12 UTC
Not quite sure why this is happening recently. 

I'm running the latest cdn versions of tailwind and daisyui and using the dark theme only. 

My form buttons that have their type specified as `submit` are rendered as outline buttons when I wanted them as plain primary color filled buttons. 
<img width="348" alt="Screenshot 2022-12-06 at 4 09 07 PM" src="https://user-images.githubusercontent.com/26633909/206023614-c2ae8410-4140-4dd5-8aba-b243d4142389.png">

Any ideas?

Keep up the great work, this project has really saved me a ton of time!

**Comment by saadeghi** [comment] 2022-12-07 09:40
It's probably duplicate of #1387 issue.  

Let me know if you have any questions.

**Closed by saadeghi** 2022-12-07 09:40 UTC
