### ISSUE TITLE
Indeterminate progress bar not working in safari

### ISSUE THREAD

**Issue by The-Real-Thisas** [saadeghi/daisyui#846] opened 2022-06-08 14:36 UTC
Description: The Indeterminate progress bar does not work on the latest version of safari.
Safari Version: Version 15.1

```html
<progress class="progress w-56"></progress>
``` 

<img width="706" alt="Screen Shot 2022-06-08 at 6 34 37 PM" src="https://user-images.githubusercontent.com/59698123/172643591-6909accc-3d44-4081-b98d-1eabe088bef8.png">

**Comment by chadwick-** [comment] 2022-07-07 18:06
The indeterminate progress bar's css makes use of the ::after pseudo-element to inject the shadow element, and animates it.   I do not think Safari (and others) [supports](https://developer.mozilla.org/en-US/docs/Web/CSS/::after#browser_compatibility) animating pseudo-elements.  

It's possible that to solve this more broadly with only CSS, there has to be two actual HTML elements (ie a "progress" element and an inner "bar" element that could be animated).    I'm certainly not an expert, so there might be another way.

**Comment by saadeghi** [comment] 2023-05-29 18:06
duplicate of #1330

**Closed by saadeghi** 2023-05-29 18:06 UTC
Labels: progress
