### ISSUE TITLE
bug: Specific classes don't work in ReactJS

### ISSUE THREAD

**Issue by rungtavaidik** [saadeghi/daisyui#1763] opened 2023-04-19 17:10 UTC
### What version of daisyUI are you using?

2.51.5

### Describe your issue

I'm using DaisyUI with ReactJS in an Electron app. The classes `input-error input-warning` etc.. don't work in a react component when using state to change className on form submit. Code:-
```js
import { useState } from 'react'
//const history = createBrowserHistory();

const Login = () => {
  const { useNavigate } =require( 'react-router-dom')
const navigate = useNavigate();
    const [name, setName] = useState('')
    const [pass, setPass] = useState('')
    const [formError, setFormError] = useState({})

    const handleSubmit = (event) => {
        event.preventDefault()

        setFormError({})

        if (name !== 'admin') {
            setFormError((prev) => ({
                ...prev,
                name: 'input input-bordered input-error',
            }))
        }

        if (pass !== 'APF@219') {
            setFormError((prev) => ({
                ...prev,
                pass: 'input input-bordered input-error',
            }))
        } else {
          navigate('/dash')
        }
    }

 

    return (
        <div className='hero min-h-screen bg-base-200'>
            <div className='hero-content flex-col lg:flex-row-reverse'>
                <div className='card flex-shrink-0 w-full max-w-sm shadow-2xl bg-base-100'>
                    <div className='card-body'>
                        <form onSubmit={handleSubmit}>
                            <div className='form-control'>
                                <label className='label'>
                                    <span className='label-text'>Username</span>
                                </label>
                                <input
                                    id='floatingInput'
                                    type='text'
                                    placeholder='Username'
                                    className={`border  ${
                                        formError['name']
                                            ? formError['name']
                                            : 'input input-bordered'
                                    }`}
                                    value={name}
                                    onChange={(e) => setName(e.target.value)}
                                />
                            </div>
                            <div className='form-control'>
                                <label className='label'>
                                    <span className='label-text'>Password</span>
                                </label>
                                <input
                                    id='floatingPassword'
                                    type='password'
                                    placeholder='Password'
                                    value={pass}
                                    className={`border ${
                                        formError['pass']
                                            ? formError['pass']
                                            : 'input input-bordered'
                                    }`}
                                    onChange={(e) => setPass(e.target.value)}
                                />
                            </div>
                            <div className='form-control mt-6'>
                                <button
                                    className='btn btn-outline no-animation btn-warning'
                                    type='submit'
                                >
                                    Login
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    )
}

export default Login
```
Whereas on the other hand classes like `input-ghost` work very well...

### What browsers are you seeing the problem on?

Chrome

**Comment by rungtavaidik** [comment] 2023-04-19 17:15
Manually adding CSS to change the border color works....

**Comment by saadeghi** [comment] 2023-04-19 17:26
First make sure the path to all your template files is addressed in `tailwind.config.js`  

If that's not the issue, please provide a sample repo so I can reproduce the problem.  

Because what you're describing, sounds like a bad TailwindCSS config. daisyUI doesn't process class names. It just adds new class names to Tailwind CSS and if the config is correct, Tailwind CSS is expected to generate all the class names based on the strings it finds in your template files.

**Comment by rungtavaidik** [comment] 2023-04-19 17:32
> First make sure the path to all your template files is addressed in `tailwind.config.js`
> 
> If that's not the issue, please provide a sample repo so I can reproduce the problem.
> 
> Because what you're describing, sounds like a bad TailwindCSS config. daisyUI doesn't process class names. It just adds new class names to Tailwind CSS and if the config is correct, Tailwind CSS is expected to generate all the class names based on the strings it finds in your template files.

https://github.com/rungtavaidik/enotebook-react


Also I'm now experiencing something really weird, this is strange and never happened before even tho the tailiwnd.css file is imported correctly in index.html:
![image](https://user-images.githubusercontent.com/122138632/233154526-6fd75fa3-6564-4df0-87fa-150f26563b97.png)
![image](https://user-images.githubusercontent.com/122138632/233154548-5f3ce533-3c7f-4ba4-9a11-0f72e4ce855f.png)

**Comment by saadeghi** [comment] 2023-04-19 18:18
> https://github.com/rungtavaidik/enotebook-react

I can't run it.
```
Failed to compile.

Module not found: Error: Can't resolve 'fs' in '/enotebook-react/node_modules/dotenv/lib'
ERROR in ./node_modules/dotenv/lib/main.js 1:11-24
Module not found: Error: Can't resolve 'fs' in '/enotebook-react/node_modules/dotenv/lib'

ERROR in ./node_modules/dotenv/lib/main.js 2:13-28
Module not found: Error: Can't resolve 'path' in '/enotebook-react/node_modules/dotenv/lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
        - install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "path": false }

ERROR in ./node_modules/dotenv/lib/main.js 3:11-24
Module not found: Error: Can't resolve 'os' in '/enotebook-react/node_modules/dotenv/lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "os": require.resolve("os-browserify/browser") }'
        - install 'os-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "os": false }

webpack compiled with 3 errors
```

**Comment by saadeghi** [comment] 2023-04-19 18:20
But your CSS file is named `input.css` and you're linking `tailwind.css`

**Comment by rungtavaidik** [comment] 2023-04-20 03:34
@saadeghi Try running it now, also I'm linking tailwind.css because the input.css has the tailwindcss directives whereas the output of those directives is in tailwind.css

**Comment by rungtavaidik** [comment] 2023-04-20 07:17
@saadeghi Try running it now, also I'm linking tailwind.css because the input.css has the tailwindcss directives whereas the output of those directives is in tailwind.css
Also i have the tailwind.css in git ignore since it's a large file...

**Comment by rungtavaidik** [comment] 2023-04-20 12:57
![image](https://user-images.githubusercontent.com/122138632/233373046-fff2855a-af3a-4d86-acd9-020714eac1c8.png)
The navbar too is messed up...

**Comment by saadeghi** [comment] 2023-04-21 02:39
The repo you shared with me has problems. I don't know how you're building `tailwind.css` file. I'm guessing you're running a global npm package.  

Anyway,
instead of using `<link rel="stylesheet" href="tailwind.css">`, import your CSS file in `src/App.js` file like this:
```
import "./input.css";
```
This way, you don't need to build another file named `tailwind.css` and ignore it. Your app will handle the CSS file itself.

Let me know if you had any questions.

**Closed by saadeghi** 2023-04-21 02:39 UTC
