### ISSUE TITLE
DaisyUI compile unused CSS from HTML text

### ISSUE THREAD

**Issue by zukilover** [saadeghi/daisyui#748] opened 2022-04-24 07:16 UTC
Hi.

This is a strange issue that I've encountered recently.
When your HTML contains any text that matches component names, it compiles the component even though it is not being used in any classes inside of the HTML file.

Example:
Given this tag in HTML, `<p>A paragraph that contains a menu text.</p>`

Run `yarn build`, and you'll see `.menu` styles being compiled in the CSS.

**Comment by saadeghi** [comment] 2022-04-24 12:29
That's expected behavior and that's how Tailwind CSS class detection works:  
![IMG_20220424_165451](https://user-images.githubusercontent.com/7342023/164976401-6226d99e-ddb2-4a4b-b721-5817a5c8e6ba.jpg)

If you have `m-10` in your content, the `m-10` class will be included. The reason is, Tailwind CSS has no idea about our framework or templating language and detects all strings as potential class name (and it's understandable)

In my opinion a few unused class name won't hurt but if you want to make sure all unused class names are getting purged, you can use a prefix for both Tailwind CSS and daisyUI.

**Closed by saadeghi** 2022-04-24 12:29 UTC
