### ISSUE TITLE
bug: closed modal still focusable

### ISSUE THREAD

**Issue by Atmos4** [saadeghi/daisyui#2876] opened 2024-02-28 15:40 UTC
### What version of daisyUI are you using?

v4.7.2

### Which browsers are you seeing the problem on?

All browsers

### Reproduction URL

https://play.tailwindcss.com/iFzG1xCAcv

### Describe your issue

When a modal is closed, it can still receive focus (i.e. from keyboard). 

This is a known conundrum about animating modals: 
- if you apply `visibility: hidden` to closed modal styles, closing transition will not display properly (can be fixed with `transition-behavior: allow-discrete` but browser support is very bad). 
- if you don't apply `visibility: hidden`, the modal will be focusable even when closed.

A fix for this would be:
- warn about this issue in the documentation
- add an example in the docs that fixes this issue with Javascript.

_Note: maybe there is another solution to this problem using some other technique that I don't know about._

Let me know if you want me to create a PR for this!

**Comment by saadeghi** [comment] 2024-04-04 18:44
duplicate of #2223

**Closed by saadeghi** 2024-04-04 18:44 UTC
