### ISSUE TITLE
Build error when import custom tailwind .css file

### ISSUE THREAD

**Issue by vnugent** [saadeghi/daisyui#1021] opened 2022-08-14 11:16 UTC
Firstly, thank you for sharing such as useful project with us.

I'm trying to add Daisy to an existing NextJS + Tailwind project.   For some reason, the build doesn't work (it can't find standard Tailwind classes) if I import a custom .css file where I define custom classes (a fairly common practice for next/react + tailwind)

```
...
wait  - compiling...

🌼 daisyUI components 2.24.0  https://github.com/saadeghi/daisyui
  ✔︎ Including:  base, components, themes[1], utilities

error - ./src/styles/global.css:1:1
Syntax error: ~/git/openbeta/open-tacos/node_modules/tailwindcss/components.css The `text-neutral-800` class does not exist. If `text-neutral-800` is a custom class, make sure it is defined within a `@layer` directive.

> 1 | @tailwind components;
    | ^
  2 |

```
global.css

```
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";

// build works OK if I comment the following 2 lines
@import './algolia.css';  
@import './defaults.css';
```

tailwind.config.js
```javascript
const defaultTheme = require('tailwindcss/defaultTheme')
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx}',
    './src/components/**/*.{js,ts,jsx,tsx}'
  ],
  // purge: ['./src/**/*.js'],
  plugins: [require('daisyui')],
  theme: {
    extend: {
  // customize default theme, etc.
  }
  },
  daisyui: {
    styled: true,
    themes: false,
    base: true,
    utils: true,
    logs: true,
    rtl: false,
    prefix: 'daisy',
    darkTheme: 'dark'
  }
}
```
postcss.config.js
```javascript
module.exports = {
  plugins: {
    'postcss-import': {},
    autoprefixer: {},
    tailwindcss: {}
  }
}
```

**Comment by vnugent** [comment] 2022-08-14 11:43
Upon additional debugging, the problem is `text-neutral-800` class.  Error:
```
 The `text-neutral-800` class does not exist. If `text-neutral-800` is a custom class, make sure it is defined within a `@layer` directive.
```

global.css
```javascript
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";

.foo {
    @apply text-blue-800;  // OK
}

.bar {
   @apply text-neutral-800; //  Error:  The `text-neutral-800` class does not exist. 
}

```

**Comment by OguzcanKarakoc** [comment] 2022-08-14 12:32
hmm, I just tested this as well. Here is a broken/working example: https://play.tailwindcss.com/JKLTaz4yHb

If you remove the `require('daisyui')` the editor shows the color (text-neutral-700). After some playing around, I found that daisyui overrides `neutral` in `src/colors/index.js`/ inside the `colorObject`. If you remove this single line, it will work. I do not know if this was by mistake or intentionally.

**Comment by OguzcanKarakoc** [comment] 2022-08-14 12:33
Obviously I do not recommend changing anything in `node_modules`, but making a pull request or maybe the creator can change it. Like I said, I am not aware if this is by choice or not.

**Comment by negprof** [comment] 2022-08-15 15:53
Hello,

we also extended our tailwind project with daisy. Really lovly components, but we also face the problem that the -neutral- colors are overwritten bei daisyui.

Is this a bug in the current daisy build?

**Comment by saadeghi** [comment] 2022-08-15 15:58
duplicate of https://github.com/saadeghi/daisyui/issues/683

Let me know if you have any questions

**Closed by saadeghi** 2022-08-15 15:58 UTC

**Comment by negprof** [comment] 2022-08-15 16:01
> duplicate of #683
> 
> Let me know if you have any questions

@saadeghi thank you very much for the quick response, I couldn´t find the answer through github search. 

Thank you and your team for this repo!

**Comment by vnugent** [comment] 2022-08-16 15:24
> duplicate of #683
> 
> Let me know if you have any questions

May I suggest that we add a short instruction/gotcha for existing tailwind users who have `-neutral-` in their code?  I can submit a doc PR.

**Comment by saadeghi** [comment] 2022-08-16 16:27
@vnugent I will add it to the docs tomorrow. I need to add the new note for all translation files.
