### ISSUE TITLE
Button is pressed initially when page loads on chrome

### ISSUE THREAD

**Issue by jenishStudent** [saadeghi/daisyui#89] opened 2021-06-20 04:55 UTC
I followed the code in your tutorial but when page loads the button is pressed causing the side bar to show and hide.

**Comment by saadeghi** [comment] 2021-06-20 04:58
@jenishStudent Can you please make an example of this issue on Codepen or Tailwind Play?  
Are you sure your JS isn't doing anything about this?

**Comment by jenishStudent** [comment] 2021-06-20 05:23
I dont have any js im using nextjs plus tailwind and your library

**Comment by jenishStudent** [comment] 2021-06-20 05:24
even in your documentation if you look at chrome browser you will see the button react when page initally loads

**Comment by jenishStudent** [comment] 2021-06-20 05:24
doesnt happen on safari though

**Comment by jenishStudent** [comment] 2021-06-20 05:51
@saadeghi  seems like a side menu issue where initally shows and hide

**Comment by saadeghi** [comment] 2021-06-20 11:17
@jenishStudent Here's a video when I refresh the page. Button has a small animation when page loads but it's not pressed. Also I don't see a problem about sidebar 🤔  

https://user-images.githubusercontent.com/7342023/122671928-20e8ba80-d1de-11eb-8885-9f9ea7fa2cd1.mp4

**Comment by ctwhome** [comment] 2021-06-22 17:41
I don't have that problem either. Which chrome version are you using? did you try on an instance without extensions?

**Comment by saadeghi** [comment] 2021-06-24 16:54
I'm closing this because I don't see any problem 🤷‍♂️

**Closed by saadeghi** 2021-06-24 16:54 UTC

**Comment by istr** [comment] 2023-07-04 21:42
@saadeghi the problem is exactly what you observe:

> Button has a small animation when page loads

It might be irrelevant ("no problem") when you only have some buttons below the fold. But it is highly distracting if you use this as a CTA (call-to-action) button in the header or if you have multiple buttons above the fold that are visible on load.

This seems to be a problem for multiple users and keeps coming up again, see #108, #397.
