### ISSUE TITLE
bug: localhost terminal message appearing in code file on save

### ISSUE THREAD

**Issue by paulhmurray** [saadeghi/daisyui#1671] opened 2023-03-08 01:37 UTC
### What version of daisyUI are you using?

latest stable

### Describe your issue

Hi,
So, when create a React, Typescript app. I installed DaisyUI first via pnpm and then npm. Once I have installed it within the project, and add it to the tailwind config file. Thereafter, every time I save any file in my code base, the message that is included in the terminal from daisyUI when running npm run dev gets inserted into any file i'm working on, after I save the file. Please see screenshot attached. The only way I can find to stop this is to remove the daisyUI from the project. 
![pic-selected-230308-1205-11](https://user-images.githubusercontent.com/39368141/223596521-638e8b42-0a98-4342-b947-4459cf4d012c.png)
I see this problem inside Neovim. This is the only editor I have. Sorry, I problem should download VSCode and try it. 

### Reproduction URL (optional)

https://github.com/paulhmurray/notetaker

**Comment by Kythonlk** [comment] 2023-04-19 17:48
Import component correctly and use vs code instead Neovim.

**Comment by saadeghi** [comment] 2023-04-19 21:45
Duplicate of https://github.com/saadeghi/daisyui/issues/1413#issuecomment-1336298367

**Closed by saadeghi** 2023-04-19 21:45 UTC
