### ISSUE TITLE
Change Height of line between two step

### ISSUE THREAD

**Issue by yassermohammad** [saadeghi/daisyui#825] opened 2022-05-31 05:26 UTC
Hello 
How can I customize Height of line between two steps
![Screenshot from 2022-05-31 09-49-03](https://user-images.githubusercontent.com/34732441/171099074-8d784781-c81c-4da7-8d93-66a2b4030b43.jpg)
?

**Comment by saadeghi** [comment] 2022-05-31 08:13
Duplicate of #742

**Closed by saadeghi** 2022-05-31 08:13 UTC

**Comment by yassermohammad** [comment] 2022-05-31 10:23
it is one way:

<ul class="steps steps-vertical">
    <li class="step step-primary">Register</li>
    <li class="step after:!w-6 after:!h-6 !h-32 before:!h-[calc(100%-.95rem)]">Receive Product</li>
</ul>

the "!h-32" will set for whole of a step to 32px
the before:!h-[calc(100%-.95rem)]" will set height line between two step to calc(100%-.95rem)
I hope this help anybody...
