### ISSUE TITLE
select-sm display incorrectly

### ISSUE THREAD

**Issue by aiguoli** [saadeghi/daisyui#76] opened 2021-06-03 07:37 UTC
hello, my code is
```html
<body class="font-mono bg-gray-100 h-full p-8">
  <form class="container mx-auto w-1/2 flex flex-col space-y-3">
...
  <select class="select select-bordered select-sm w-full"">
    <option disabled="disabled" selected="selected">select</option>
    <option>1</option>
    <option>2</option>
  </select>
...
  </form>
</body>
```

but it displayed like this, the `option` is incomplete.
![image](https://user-images.githubusercontent.com/49404623/120605991-46a55e00-c481-11eb-8b95-1ce2cb661942.png)

**Comment by atresnjo** [comment] 2021-06-03 14:53
Maybe some other CSS overriding it? Here's an [example ](https://play.tailwindcss.com/CUAgnzB1BR) with your code, which displays the value correctly.

**Comment by saadeghi** [comment] 2021-06-03 15:32
I think @atresnjo is right. To debug this issue. You need to compare the style from your inspect element with the example @atresnjo made. It might be a style from a container or another element. Something like a font size, line height, etc.  
I'm closing this issue since it's not a bug from daisyUI but feel free to continue the conversation. I would be glad to help if I get more details about your code.

**Closed by saadeghi** 2021-06-03 15:32 UTC

**Comment by aiguoli** [comment] 2021-06-04 09:15
Thanks for your answer.
But it's so wired that I copy my code into play page, it works perfect. 😭

code: https://play.tailwindcss.com/NDaYmAmRQr

play:
![image](https://user-images.githubusercontent.com/49404623/120777178-9a827680-c557-11eb-97e9-6d4ec2760485.png)
local:
![image](https://user-images.githubusercontent.com/49404623/120777223-a2dab180-c557-11eb-8cdd-ce95d989cec2.png)
local(delete `select-sm`):
![image](https://user-images.githubusercontent.com/49404623/120777278-b4bc5480-c557-11eb-9436-314cb972797c.png)

**Comment by saadeghi** [comment] 2021-06-04 10:12
@aiguoli Can you try adding a `py-0` class to `<input>`?  
Based on that I see on the screenshot, it looks like there's a padding. I added a `py-2` class and [the result](https://play.tailwindcss.com/w9amuD6s94) became similar to yours.
You need to check inspect element to see if there's a padding style for `input` and find the source of it.

**Comment by aiguoli** [comment] 2021-06-04 10:22
it works perfectly, thank you so much!!!😀

**Comment by roelandmoors** [comment] 2023-08-22 16:48
I had this problem because the '@tailwindcss/forms' plugin was also loaded.

**Comment by CPAanalytics** [comment] 2024-07-30 21:27
> I had this problem because the '@tailwindcss/forms' plugin was also loaded.
