### ISSUE TITLE
docs: change Next.js example repository to use the app directory

### ISSUE THREAD

**Issue by hb20007** [saadeghi/daisyui#1847] opened 2023-05-29 12:43 UTC
### On which page do you see this issue?

https://daisyui.com/docs/install/

### Describe the issue

The Next.js example repository uses the `pages` instead of the `app` directory. As mentioned in the [Next.js 13.4 release blog post](https://nextjs.org/blog/next-13-4), the App router is now considered stable and production-ready. So, the main example repository for Next.js should be based on this now-recommended approach. The existing one with the `pages` directory can be either removed or kept in case somebody would want to refer to it.

**Comment by daniimendes22** [comment] 2023-05-29 20:02
Can I do this?

**Comment by saadeghi** [comment] 2023-05-29 20:18
> That would be great 🙏  
You can [fork it from here](https://stackblitz.com/edit/daisyui-nextjs), install new dependencies and apply file structure changes. Then give me the link to update.

**Comment by saadeghi** [comment] 2023-06-07 14:11
It looks like Next.js 13 on Stackblitz can not process Post CSS  probably because SWC is written in Rust and the binary can not work in StackBlitz:

https://stackblitz.com/edit/stackblitz-starters-rzdbmx

Their suggested workaround doesn't work either: https://nextjs.org/docs/messages/failed-loading-swc

I'm keeping the Stackblitz example on Next 12 for now until the issue is fixed by Next or StackBlitz.

**Closed by saadeghi** 2023-06-07 14:11 UTC
