### ISSUE TITLE
bug: safari v16.2 (18614.3.7.1.5) on MacOS 13.1 (22C65)

### ISSUE THREAD

**Issue by dsm-72** [saadeghi/daisyui#1590] opened 2023-02-11 14:53 UTC
### What version of daisyUI are you using?

2.50.0

### Describe your issue

Button, on hover, shows red 

https://user-images.githubusercontent.com/100158155/218265235-18362ade-9210-4d5a-88d2-ffef7e3e2124.mov

### What browsers are you seeing the problem on?

Safari

**Comment by saadeghi** [comment] 2023-02-11 22:13
Can you give me a code example on [Tailwind Play](https://daisyui.com/tailwindplay/) or a GitHub repo?  

- Do you see this issue on daisyUI website as well?
- Do you have any other CSS or JS code that may manipulate the style of that button?

**Comment by dsm-72** [comment] 2023-02-12 13:35
@saadeghi 

- On the daisyUI website? no.
- Other styles? Not to my knowledge.


```tailwind.config.cjs
const { space } = require('svelte/internal')
const defaultTheme = require('tailwindcss/defaultTheme')
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,js,svelte,ts}'],
  theme: {
    maxWidth: {
      '1/2': '50%',
      '1/4': '25%',
      '1/3': '33%',
      '1/6': '16%',
      '1/8': '12%',
      '96': '24rem',
    },
    maxHeight: {
      '1/2': '50%',
      '1/4': '25%',
      '1/3': '33%',
      '1/6': '16%',
      '1/8': '12%',
      '96': '24rem',
      '100': '25rem',
      '104': '26rem',
      '108': '27rem',
      '112': '28rem',
      '116': '29rem',
      '118': '29.5rem',
      '120': '30rem',
      '124': '31rem',
      '128': '32rem',
    },
    purples: { // purple
      "primary": "#ddd6fe",          
      "secondary": "#a5b4fc",                
      "accent": "#8b5cf6",                
      "neutral": "#9ca3af",                
      "base-100": "#f3f4f6",                
      "info": "#67e8f9",                
      "success": "#6ee7b7",                
      "warning": "#fde047",                
      "error": "#F87272",
    },
    extend: {
      spacing: {        
        '62': '15.5rem',
        '80': '20rem',
        '84': '21rem',
        '88': '22rem',
        '92': '23rem',
        '96': '24rem',
        '100': '25rem',
        '104': '26rem',
        '108': '27rem',
        '112': '28rem',
        '116': '29rem',
        '118': '29.5rem',
        '120': '30rem',
        '124': '31rem',
        '128': '32rem',
      },
      fontFamily: {
        'sans': [...defaultTheme.fontFamily.sans],
        'serif': ['Quicksand', ...defaultTheme.fontFamily.sans],
        'mono': ['SpaceMono', ...defaultTheme.fontFamily.sans],
        'quicksand': ['Quicksand'],
        'bellota': ['Bellota'],
        'bellotatext': ['BellotaText'],
        'spacemono': ['SpaceMono'],
        'inconsolata': ['Inconsolata'],
      },
      fontSize: {
        'xs': ['0.6rem', '0.8rem'],
        '2xs': ['0.4rem', '0.6rem']
      },
      screen: {
        'xs': '512px',
        '2xs': '400px',
        '2xl': '1536px',
        '3xl': '1600px',
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
    require('@tailwindcss/container-queries'),
    require('@tailwindcss/line-clamp'),
    require("daisyui"),
  ],
}
```

**Comment by dsm-72** [comment] 2023-02-12 13:37
Also I am finding that dropdown click doesn't work on safari as well.
What could be happening?

**Comment by dsm-72** [comment] 2023-02-14 19:47
@saadeghi any idea why click on dropdown won't work?

**Comment by saadeghi** [comment] 2023-02-15 08:24
I need a code example on a Tailwind Play page or a GitHub repo where I can reproduce the issue.  
Sharing your `tailwind.config.js` can't help here because there's nothing in there related to this problem.

**Comment by kamyabnazari** [comment] 2023-05-26 08:49
@saadeghi still the same problem on safari, but it works on other browsers. What informations do you need to debug this, I can try to send it here.

**Comment by saadeghi** [comment] 2023-05-26 16:59
If the problem exists on [Tailwind Play](https://daisyui.com/tailwindplay/) or daisyUI website, the problem is from the daisyUI.  
But if it only exists on your project, the issue is not daisyUI or Safari. So I need a minimal reproduction repo to see your project. 

Maybe it's an external CSS code. maybe a problem is with the build setup. maybe it's a bug on another dependency. 

...I can't tell unless I see the project.

I'm going to close this because because it doesn't look like a issue from daisyUI but feel free to continue the conversation here or on a [discussion](https://github.com/saadeghi/daisyui/discussions). I can help more if someone provides an example repo with the issue.

**Closed by saadeghi** 2023-05-26 16:59 UTC
