### ISSUE TITLE
bug: daysiui + @tailwindcss/forms for checkboxes and collapse

### ISSUE THREAD

**Issue by flesage-000** [saadeghi/daisyui#2131] opened 2023-07-13 16:06 UTC
### What version of daisyUI are you using?

3.2.1

### Describe your issue

hi,

there are incompatibilities between daysiUi and @tailwindcss/forms (0.5.3) with:
- the checkboxes, a tick appears in addition to the point on the right
  - screenshot showing normal view ![image](https://github.com/saadeghi/daisyui/assets/14925145/4f216d2d-3af5-4b2e-91f6-6483df6f1de5)
  - screenshot showing modified view by disabling box-shadow style in devTools ![image](https://github.com/saadeghi/daisyui/assets/14925145/6c1092e8-2fad-49d5-9b42-1b3fa77088a5)

- the "collapse", @tailwindcss/forms forces the checkbox/radio input with "1rem" in width, which makes the collapse inoperative, except for an area on the left of the collapse. 
  - screenshot showing the style modifying the behavior of the collapse checkbox (height and width are striked cause i used "h-auto, w-auto to debug)
![image](https://github.com/saadeghi/daisyui/assets/14925145/d41b06c6-aa28-4bdc-98a1-fdcf10a53b1d)

Being still new to DaisyUi (which is really great!), I don't intend to use @tailwindcss/forms anymore. I am only warning of this incompatibility.

note:
- in the browser used I put "Chrome", but I use OperaGX (which is essentially the same thing)

### What browsers are you seeing the problem on?

Chrome

**Comment by saadeghi** [comment] 2023-07-14 07:57
Duplicate of https://github.com/saadeghi/daisyui/issues/1431#issuecomment-1347822839

**Closed by saadeghi** 2023-07-14 07:57 UTC
