### ISSUE TITLE
bug: toogle button is not working on Nextjs 13.4

### ISSUE THREAD

**Issue by aimehai** [saadeghi/daisyui#1927] opened 2023-06-06 07:20 UTC
### What version of daisyUI are you using?

v3.0.3

### Describe your issue

When it appear: ![image](https://github.com/saadeghi/daisyui/assets/125627850/1b8e7858-2203-491d-b3c8-fc94aca5fcd4)
When i clicked: ![image](https://github.com/saadeghi/daisyui/assets/125627850/a8d33fcf-8a3d-481b-b192-679223d8c1ac)
It changed to: ![image](https://github.com/saadeghi/daisyui/assets/125627850/d97b48f2-973c-47fc-a80f-3b4685155bc9)
When i clicked outside the button: ![image](https://github.com/saadeghi/daisyui/assets/125627850/39ae168a-1432-45d1-ae3c-dc500cf744d0)
My code: 
![image](https://github.com/saadeghi/daisyui/assets/125627850/60103f42-7bcb-49a8-82a5-36c3755808af)

Can anyone help me? 

### What browsers are you seeing the problem on?

Chrome

**Comment by saadeghi** [comment] 2023-06-06 23:51
Duplicate of https://github.com/saadeghi/daisyui/issues/1431

**Closed by saadeghi** 2023-06-06 23:51 UTC
