### ISSUE TITLE
bug: v3 focus and active on a menu item don't play nice together

### ISSUE THREAD

**Issue by johnslemmer** [saadeghi/daisyui#1887] opened 2023-06-01 22:41 UTC
### What version of daisyUI are you using?

3.0.0

### Describe your issue

If you manually toggle state :focus on the active menu item on the daisy docs website this  becomes apparent.  The two classes don't mesh well together.  I noticed this because my app keeps focus on my `menu` based sidebar when switching between pages. v2 didn't have this issue, I think it let `active` be the overriding class.

<img width="1710" alt="image" src="https://github.com/saadeghi/daisyui/assets/18610918/aadeedea-06c7-448c-95d7-8209225ec124">

### What browsers are you seeing the problem on?

Chrome

**Comment by Andrew67** [comment] 2023-06-02 04:08
Looks like a duplicate of https://github.com/saadeghi/daisyui/issues/1868 filed slightly earlier which has a few workarounds discussed.

**Comment by saadeghi** [comment] 2023-06-20 22:28
Fixed

**Closed by saadeghi** 2023-06-20 22:28 UTC
