### ISSUE TITLE
bug: custom theme not applied

### ISSUE THREAD

**Issue by kevinXmichael** [saadeghi/daisyui#2224] opened 2023-08-06 06:50 UTC
### What version of daisyUI are you using?

v3.5.1

### Describe your issue

When generating a custom theme with the help of the [theme generator](https://daisyui.com/theme-generator/) and applying it in the `tailwind.config.js`, the custom colors are not reflected in the UI. Even overriding existing themes is not working.

## tailwind.config.js

```js
/** @type {import('tailwindcss').Config} */

const extensions = '*.{tsx,scss}'

module.exports = {
  content: [
    `./src/app/**/${extensions}`,
    `./src/components/**/${extensions}`,
    `./src/styles/**/${extensions}`
  ],
  theme: {
    extend: {}
  },
  daisyui: {
    // themes: false,
    themes: [
      {
        mytheme: {
          primary: '#000000',
          secondary: '#009EE0',
          accent: '#D1172F',
          neutral: '#ffffff',
          'base-100': '#2a323c',
          info: '#009EE0',
          success: '#16a34a',
          warning: '#fbbd23',
          error: '#D1172F'
        }
      }
    ],
    darkTheme: 'dark', // name of one of the included themes for dark mode
    base: true, // applies background color and foreground color for root element by default
    styled: true, // include daisyUI colors and design decisions for all components
    utils: true, // adds responsive and modifier utility classes
    rtl: false, // rotate style direction from left-to-right to right-to-left. You also need to add dir="rtl" to your html tag and install `tailwindcss-flip` plugin for Tailwind CSS.
    prefix: '', // prefix for daisyUI classnames (components, modifiers and responsive class names. Not colors)
    logs: false // Shows info about daisyUI version and used config in the console when building your CSS
  },
  plugins: [require('daisyui')]
}
```

## src/app/layout.tsx (using Next.js 13)

```ts
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" data-theme="mytheme">
      <body className="bg-primary m-auto flex flex-col items-center">{children}</body>
    </html>
  )
}
```

### What browsers are you seeing the problem on?

All browsers

**Comment by saadeghi** [comment] 2023-08-06 21:03
Are you sure the problem is not with something else?  
Like:   
- build steps
- cache
- wrong file path (make sure this is indeed your `tailwind.config.js` file, based on framework or build tool, maybe the actual file should be somewhere else)
- ...

Your config looks correct.  

Here's your exact config and your custom theme and you can see it's working as expected:   
https://play.tailwindcss.com/VVpwj2SDpp?file=config

I'm closing this because it's not an issue from daisyUI but feel free to continue the conversation until the problem is solved.  
Let me know if you have any questions.

**Closed by saadeghi** 2023-08-06 21:03 UTC

**Comment by kevinXmichael** [comment] 2023-08-06 21:05
You are right! You fork works fine, my issue was the following: I had a Button component which calculated the color dynamically:
className={"btn btn-${props.color ?? 'primary'}"}
The issue is that the tailwind compiler will not recognise this so I changed it to always provide full class names:
className={"btn ${props.color ?? 'btn-primary'}"}
With this approach every time a pass a color the compiler will now to provide these classes.

**Comment by saadeghi** [comment] 2023-08-06 21:59
>The issue is that the tailwind compiler will not recognise this

Yes. This is a common problem from devs. Not only with daisyUI class names but also with Tailwind CSS class names (for example people write half variable `bg-{$color}-500`)  

Tailwind docs warned about this, I also mentioned this in daisyUI FAQ.

If you think about it, Tailwind doesn't really have any way to recognize the class name this way. It just reads your template files before you run/compile your template, so that variable can be anything.
