### ISSUE TITLE
Clicking button that triggers dropdown should also collapse the dropdown on second click

### ISSUE THREAD

**Issue by aaronshaf** [saadeghi/daisyui#491] opened 2022-02-20 01:08 UTC
Compare:

https://instructure.design/#Menu

Thanks for making DaisyUI. It's great!

**Comment by aaronshaf** [comment] 2022-02-20 01:10
This change would complement well with a Swap'd button.

**Comment by saadeghi** [comment] 2022-02-21 05:28
Duplicate of #157

**Closed by saadeghi** 2022-02-21 05:28 UTC
