### ISSUE TITLE
Using the drawer : scroll position is not kept when the page is refresh

### ISSUE THREAD

**Issue by slevy85** [saadeghi/daisyui#1180] opened 2022-09-24 17:55 UTC
Hi first of all thank you very for this great library !

I noticed that when we use the drawer, the scroll position is not kept when we refresh the page, we can see a live example in the documentation website.

Is there a way to fix this ?

Thank you very much ?

**Comment by NN77** [comment] 2022-10-02 18:01
Having the same issue. This is quite important as, without the fix, I'll have to revert to using the drawer all.

**Comment by NN77** [comment] 2022-10-08 14:47
Bump the topic? The issue with back to top <a href="#"></a>

**Comment by BranislavLazic** [comment] 2022-11-04 21:56
Can confirm this. `window.scrollY` is not being caught when `drawer` and `drawer-content` classes are applied.

**Comment by saadeghi** [comment] 2022-11-04 22:13
The problem is, `drawer` is a wrapper div and when we use `drawer` instead of the `window`, the `drawer-content` scrolls because that's where the page content is. This is the only way we can have dynamic off-canvas sidebar on demand.  
But it comes at a price, the browsers, unfortunately don't restore the div scroll when we get back to a page. They only restore the `window` scroll position. I hope it gets fixed in the future but for now, the only way is using JS to save/restore the scroll position (which is not a perfect way either)

@BranislavLazic `window.scrollY` doesn't work because instead of `window`, the `drawer-content` is getting scrolled so if you want to read/edit the scroll position or apply scroll-behavior, you should do it for the `drawer-content` instead of `window`

I should unfortunately close this issue because there's no fix for it unless future version of browsers, keep the scroll positions of all elements as well as the `window`

**Closed** 2022-11-04 22:13 UTC
Labels: wontfix
