### ISSUE TITLE
bug: DaisyUI hangs Docker builds for 64 bit platforms

### ISSUE THREAD

**Issue by nsadeh** [saadeghi/daisyui#3030] opened 2024-05-10 17:32 UTC
### What version of daisyUI are you using?

4.10.5

### Which browsers are you seeing the problem on?

All browsers

### Reproduction URL

not a UI issue

### Describe your issue

I have a server-rendered project that uses DaisyUI. It's being deployed on Google Cloud Run, which requires docker containers to be built for 64bit platforms.

When I run the build command for Docker (see below), the build hangs at the `npm run build` command perpetually. If I remove dailyui from the plugins list in `tailwind.config.js`, then the build runs just fine. I can also keep Daisy, but then I have to drop the platform spec from the docker build command, which makes the image undeployable in GCP.

Here's my Dockerfile:
```Dockerfile
# Stage 1: Build the project
FROM amd64/node:buster AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json (or npm-shrinkwrap.json) for npm install
COPY package*.json ./
COPY elm-tooling.json ./

# Install dependencies
RUN npm cache clean --force
RUN npm install

# Copy the rest of your application's source code from your host to your image filesystem.
COPY . .

# Build the project
RUN npm run build

# Stage 2: Setup the runtime environment
FROM amd64/node:buster-slim

# Set the working directory
WORKDIR /app

# Copy the build output from the previous stage
COPY --from=builder /app/dist dist
COPY --from=builder /app/dist-server dist-server

# Install production dependencies only
# This is helpful if your dist-server relies on node_modules like koa and koa-static
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/elm-tooling.json ./
RUN npm install

# Expose the port the app runs on
# EXPOSE 8080
RUN echo $PORT
EXPOSE $PORT

# Run the server
CMD ["node", "dist-server/server.mjs"]
```

Here's the build command:
```
docker build  -t $IMAGE_TAG --platform linux/amd64 .
```

When DaisyUI is included in the Tailwind config, the build step looks like this:
```
#15 [builder 8/8] RUN npm run build
#15 0.691
#15 0.691 > build
#15 0.691 > npm run generate-all && elm-pages build
#15 0.691
#15 1.296
#15 1.296 > generate-all
#15 1.296 > npm run generate:tailwind
#15 1.296
#15 1.902
#15 1.902 > generate:tailwind
#15 1.902 > postcss tailwind.css -o src/tailwind-compiled.css
#15 1.902
#15 2.715
#15 2.715 🌼   daisyUI 4.10.5
```

It's stuck there perpetually. When it's not included in the config, it builds (although none of the daisy classes or themes are included). If I remove the `--platform linux/amd64` but keep the DaisyUI, it also builds fine, but is undeployable in GCP.

**Comment by saadeghi** [comment] 2024-05-10 17:56
It's probably an issue from one of the build tools or their dependencies. And since it's not giving an error, it's not easy to guess which one is the problem.  
Unfortunately there's nothing I can fix about it on our side.   

Can you try with the latest version of Node and the latest version of all NPM dependencies?

**Comment by nsadeh** [comment] 2024-05-10 18:30
Here are my dependencies:

```
  "devDependencies": {
    "@fullhuman/postcss-purgecss": "^6.0.0",
    "autoprefixer": "^10.4.19",
    "concurrently": "^8.2.2",
    "daisyui": "^4.10.5",
    "elm-codegen": "^0.5.3",
    "elm-optimize-level-2": "^0.3.5",
    "elm-pages": "^3.0.14",
    "elm-review": "^2.11.1",
    "elm-tooling": "^1.15.1",
    "lamdera": "^0.19.1-1.2.1-1",
    "postcss": "^8.4.38",
    "postcss-cli": "^11.0.0",
    "tailwindcss": "^3.4.3",
    "vite": "^5.2.10",
    "vite-plugin-webfont-dl": "^3.9.3"
  },
  ````

Here is a simplified dockerfile that has the same issue:

```Dockerfile
# Stage 1: Build the project
FROM node:latest AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json (or npm-shrinkwrap.json) for npm install
COPY package*.json ./
COPY elm-tooling.json ./

# Install dependencies
RUN npm cache clean --force
RUN npm install

# Copy the rest of your application's source code from your host to your image filesystem.
COPY . .

# Build the project
RUN npm run build

CMD ["echo" "Hello there!"]
```

It still hangs.

I realize this is a difficult bug to solve. Could it be in the Tailwind plugin code rather than DaisyUI?

**Comment by saadeghi** [comment] 2024-05-10 20:11
You don't need `@fullhuman/postcss-purgecss` anymore (it was only needed for older Tailwind versions) Here's what's needed for PostCSS setup:  
https://tailwindcss.com/docs/installation/using-postcss

Also you can try using TailwindCSS CLI instead of `postcss` and `postcss-cli`:  
https://tailwindcss.com/docs/installation

**Comment by nsadeh** [comment] 2024-05-10 20:31
I'll try that setup. I use a framework called elm-pages which runs with Vite, and haven't had luck with tailwind cli so far which is why I used postcss this far.

At this point I removed Daisy UI from my project and refactored it out so the deploy can proceed, but if I have time this weekend I'll try to work it back in.

**Comment by saadeghi** [comment] 2024-05-10 20:39
I'm going to close this issue because the problem can't be from daisyUI. it's probably one of build tools.  
Feel free to continue the conversation and let me know if you have any questions.

**Closed by saadeghi** 2024-05-10 20:39 UTC

**Comment by AndreyBarkov** [comment] 2024-08-13 18:55
I have a similar issue building a docker image for my Rails app on macOS. I'm running `docker build --platform="linux/amd64"` to build docker image locally. 
These are the logs without DaisyUI in my tailwind config, which takes about 7.2s to `precompile` assets:
![image](https://github.com/user-attachments/assets/abc5c963-f596-4f1c-bae5-d2175f86ae94)
And this is what I see when I include DaisyUI in my tailwind config:
![image](https://github.com/user-attachments/assets/62c48cae-f78a-4c8f-80d0-0a95462cee3b)

It sits there forever, and I couldn't produce any additional logs. However, when I run the `precompile` command outside of docker, it takes just a couple of seconds to finish with DaisyUI. Running on Node v20 with the following dependencies:
```
{
  "dependencies": {
    "daisyui": "^4.4.4",
    "logrocket": "^8.1.0",
    "stimulus-autocomplete": "^3.1.0",
    "tailwindcss": "^3.3.5",
    "@tailwindcss/forms": "^0.5.7",
    "@tailwindcss/line-clamp": "^0.4.4"
  },
  "engines": {
    "node": "^20.x"
  },
  "devDependencies": {
    "prettier-plugin-erb": "^0.4.0"
  }
}
```

**Comment by saadeghi** [comment] 2024-08-14 01:13
@AndreyBarkov can you share the setup pipeline for tour CSS file? How are you generating the CSS? Is it Tailwind CLI?

**Comment by nickhammond** [comment] 2024-08-30 20:55
Just started experiencing this as well, going to probably end up switching to another component library but would love to figure out what's going on. Anyone on this thread resolve the issue?

Utilzing the tailwind CLI via rails assets compilation. I've tried modifying my tailwind.config.js to comment out everything but the `require('daisyui')` line but it always hangs at the same place. It looks like it's somewhere in these lines https://github.com/saadeghi/daisyui/blob/v4.12.10/src/index.js#L31-L77

```
  "devDependencies": {
    "daisyui": "^4.11.1",
    "tailwindcss": "^3.4.10"
  }
}
```

**Comment by nickhammond** [comment] 2024-08-30 21:55
Here's the simplest possible setup I could do to trigger the build hanging, it's most likely ARM specific when building for linux/amd64, removing the platform option builds just fine. Only the files below are in this directory so there's nothing for daisyui to actually do besides being required by tailwind. 

_.dockerignore_
```
node_modules
```

_Dockerfile_
```
FROM node:slim AS builder
WORKDIR /app

COPY package*.json ./

RUN npm cache clean --force
RUN npm install

COPY . .

RUN npx tailwindcss

CMD ["ls", "-lha"]
```

_package.json_
```
{
  "devDependencies": {
    "daisyui": "^4.12.10",
    "tailwindcss": "^3.4.10"
  }
}
```

_tailwind.config.js_
```
module.exports = {
  plugins: [
    require('daisyui')
  ],
}
```

```
docker build --platform linux/amd64 .
```

<img width="517" alt="image" src="https://github.com/user-attachments/assets/fc181f2e-6fda-4b60-9ff0-955b183e92a1">

**Comment by nickhammond** [comment] 2024-08-30 22:04
Figured it out. It hangs on >= node-22. Works fine on node 18 and 20.

```
FROM node:20-slim AS builder
WORKDIR /app

COPY package*.json ./

RUN npm cache clean --force
RUN npm install

COPY . .

RUN npx tailwindcss

CMD ["ls", "-lha"]
```

**Comment by jharrilim** [comment] 2024-09-28 04:34
I have the same issue, and I've confirmed that commenting out the `require('daisyui')` plugin makes the issue go away, so the issue does seem to stem from something within the daisyui plugin.

**Comment by Vagab** [comment] 2024-10-09 16:14
I'm experiencing the same error. Does anyone have a workaround in mind?

**Comment by fusion2004** [comment] 2024-11-15 21:10
Also running into this! The logs and examples others have shown mirror exactly what I'm seeing. My exact example is running tailwindcss w/ daisyui as part of precompiling assets for a rails app.

**Comment by saadeghi** [comment] 2024-11-15 21:51
Try changing or upgrading your build tool. Try updating the dependencies related to CSS process. Try changing Node version.

daisyUI is a plugin for Tailwind CSS. It adds CSS class names to Tailwind CSS. If your setup can not handle processing the CSS, it's w problem from the build tool and there's nothing we can fix on daisyUI side.

**Comment by crmne** [comment] 2024-11-26 18:57
I can confirm this issue, specifically when building a [docker](https://github.com/crmne/cluster-headache-tracker/blob/main/Dockerfile) image for linux/amd64 on macOS 15.1.1 (M1 Mac). Notably, the build doesn't hang in other environments I've tested: either on a native linux/amd64 machine (Fedora 41) or when using Lima to run a QEMU linux/amd64 VM (using [this config](https://github.com/crmne/cluster-headache-tracker/blob/main/lima-docker-amd64.yaml)) with [Lima](https://lima-vm.io/) on macOS ARM.

**Comment by khaled-badenjki** [comment] 2024-12-16 12:54
I'm also facing the same issue. It happes when i add daisyUI, everything else was working fine

**Comment by saadeghi** [comment] 2024-12-16 13:00
I understand that you're experiencing the issue WHEN you add daisyUI. But daisyUI is not the issue. Your build tool can not build the new CSS for whatever reason. There's nothing we can help about here.  
Try upgrading or changing the build tool.

**Comment by bismark64** [comment] 2025-01-15 20:51
@AndreyBarkov I have the same issue with `RUN SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile` when trying to build an image to deploy to AWS ECS using `--platform="linux/amd64"`. If I get rid of the platform flag it will not run at AWS ECS.
How did you fix it?

**Comment by Talha345** [comment] 2025-01-19 14:31
Same issue here with Rails 8 and docker.

Solutions Tried (not working):

- Downgrading Node version
- Moving from npm to yarn

**Comment by piti118** [comment] 2025-01-31 19:03
Finally... Uncheck `Use Rosetta for ...` works.

<img width="1056" alt="Image" src="https://github.com/user-attachments/assets/2e8c277f-d8f7-4209-b3c6-c211365b8ad7" />

Courtesy from @corneliusroemer. The button has moved a bit.

https://github.com/docker/for-mac/issues/6998#issuecomment-1751227323

**Comment by bellef** [comment] 2025-02-22 17:41
As a newbie using Docker, I am facing the same problem using Kamal.
However I am able to build the image using `docker build` but Kamal fails to deploy and is stuck at DaisyUI like explained above.
So it seems that the platform I am deploying to (OVH VPS) has a different architecture than my local one.
Anyone having the same issue?

**Comment by jamedeus** [comment] 2025-05-13 01:01
For anyone thinking they have this issue on **Tailwind v4**: make sure you set `WORKDIR` in your Dockerfile. 

Tailwind now does source detection automatically by scanning all files in the working directory. If you don't set WORKDIR then you will be at `/`, so Tailwind will walk the entire linux filesystem looking for source files. This looks like the build is hanging but actually just takes an extremely long time.
