### ISSUE TITLE
Typography not working as intended

### ISSUE THREAD

**Issue by goodbeysr** [saadeghi/daisyui#170] opened 2021-08-31 17:27 UTC
I couldn't make typography work after following these steps:

1. integrating `@tailwindcss/typography`
2. add `daisyui` plugin after 1.

this one is rendering h1 with light theme
![image](https://user-images.githubusercontent.com/22368199/131548256-a16e0d40-242d-4b05-bc43-fd51b188a22e.png)

and this one in dark mode
![image](https://user-images.githubusercontent.com/22368199/131548343-12e4c57f-8b48-469d-8e14-cfd9d3c1c416.png)

here is my config

> module.exports = {
  theme: {},
  variants: {},
  plugins: [require('@tailwindcss/typography'), require('daisyui')],
};

daisyui: 1.14.0
tailwindcss: 2.2.9

**Comment by tylerjlawson** [comment] 2021-09-11 17:45
The colors from @tailwindcss/typography are overriding the theme from daisyui. This would be easily avoided if there was a nice way to use the typography plugin without it's color styles.

**Comment by saadeghi** [comment] 2021-09-11 22:30
@goodbeysr can you please make an example GitHub repo so I can reproduce this bug?

**Comment by saadeghi** [comment] 2021-09-23 21:16
@goodbeysr I'm closing this because I couldn't reproduce this issue.  
Feel free to re-open it with an example repo link.

**Closed by saadeghi** 2021-09-23 21:16 UTC

**Comment by AntonTrapp** [comment] 2021-12-12 16:04
I don't know if I'm getting the documentation wrong about "daisyUI adds some style to @tailwindcss/typography" or I have the same issue. Following the example does nothing (I do have a standard h1 class that looks exatly the same in any theme as it's not styled in any way, not like the HTML in the docs where the h1, ... have a lot of prose class styling). I have to style every h1, ... with the ugly prose classes manually. (daisyui 1.16.4/tailwindcss 2.2.19).

So what "does" daisyUI add and where can I find that information? If it's doing nothing why not 1 sentence: use tailwindcss with all the prose classes manually - or: what do I have to do to make daisyUI apply the prose classes that fit the theme?

PS: everything apart from the typography seems to work out of the box, including custom theming. After a couple of minutes. I'm really impressed!

**Comment by AntonTrapp** [comment] 2021-12-12 16:44
FYI: run into that issue https://issueexplorer.com/issue/tailwindlabs/tailwindcss-typography/214 too. Typography from tailwind seems to be quite a mess with version conflicts, unresolved bugs, ... - probably better to get rid of that alltogether as the rest of daisyUI is working nice.
