### ISSUE TITLE
VS Code Tailwind CSS Intellisense Extension Issue

### ISSUE THREAD

**Issue by spietrek** [saadeghi/daisyui#464] opened 2022-02-15 18:23 UTC
Today I upgraded to daisyUI version 2.0.2. Everything installed fine; however, the Tailwind CSS Intellisense extension failed with the following error:

tailwind CSS: <css input>:4:1: Variant cannot be generated because selector contains no classes

Package.json details.

"dependencies": {
    "@vue/composition-api": "^1.4.6",
    "axios": "^0.26.0",
    "core-js": "^3.21.0",
    "daisyui": "^2.0.2",
    "vue": "^2.6.14",
    "vue-router": "^3.5.3",
    "vuex": "^3.6.2"
  },

"devDependencies": {
...,
"postcss": "^7.0.39",
...
"tailwindcss": "npm:@tailwindcss/postcss7-compat@2.2.17",
...
}

I downgraded to daisyUI 1.24.3, deleted node_modules and yark.lock, and ran 'yarn install'. The error went away and Tailwind CSS Intellisense now works.

**Comment by saadeghi** [comment] 2022-02-15 18:35
I'm not sure...  
1. Can you share a small repo so I can reproduce this?
2. Does the error print to any specific CSS style that causes the issue?
3. Can you try with Tailwind CSS 3.0 and Post CSS 8.0?

**Comment by spietrek** [comment] 2022-02-16 12:38
Here is a "smallish" repo I have been working on. https://github.com/spietrek/kk-kkoms-demo. You just need to update daisyUI to use the latest version. The error is in the Output window for the Tailwind CSS Intellisense extension. I will see if I can upgrade my Vue2 to use Tailwind CSS 3.0. I assume the issue is a conflict in PostCSS 7.

**Comment by spietrek** [comment] 2022-02-16 21:18
No issue running Vue 3, Vite, TailwindCSS 3.0, and Post CSS 8.0.

**Comment by kharann** [comment] 2022-02-16 22:25
There's an issue running Sveltekit 1.0.0-next275, postcss 8.3.5, tailwindcss 3.0.23 and daisyui 2.0.6

**Comment by joeelia** [comment] 2022-02-17 04:29
@spietrek your repo is using Vue2. Vue2 cannot use Tailwind CSS v3 because Vue2 cannot use Post CSS 8.

DaisyUI ^2.0 requires Tailwind CSS v3.

Your repo seems to be using yarn. Simply add run this command for the latest DaisyUI build that works with Vue2 and Tailwind CSS v2

`yarn add daisyui@1.25.4`

I'll take that thumbs up now. Thanks.

**Comment by saadeghi** [comment] 2022-02-17 11:09
@spietrek I can't install the dependencies on your project:
```bash
error kk-kkoms-demo/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
```
I'm not sure why you need Sass and PostCSS on the same project...  but anyway, I'm glad the problem is fixed with Vue 3  
Vue 3 and Post CSS 8 came out a year ago so I guess it's better to keep them dependencies updated.

**Closed by saadeghi** 2022-02-17 11:09 UTC
