### ISSUE TITLE
bug: missing span styles in join

### ISSUE THREAD

**Issue by ravsii** [saadeghi/daisyui#1976] opened 2023-06-11 11:58 UTC
### What version of daisyUI are you using?

v3.0.25

### Describe your issue

Since `input-group` is deprecated now and `join` is supposed to take its place, at the moment there's no way to use `input-group`'s span styles

See tailwind play for demonstration.

_Not sure if this is intentional, but this broke quite a few components in my app and I'm not sure whether I should fix it myself or wait for a fix_

### What browsers are you seeing the problem on?

Chrome, Firefox

### Reproduction URL (optional)

https://play.tailwindcss.com/eiL4fbk7En

**Comment by saadeghi** [comment] 2023-06-11 15:51
duplicate of #1964

**Closed by saadeghi** 2023-06-11 15:51 UTC
