### ISSUE TITLE
daisy and macosx installing failure

### ISSUE THREAD

**Issue by docgonzo2015** [saadeghi/daisyui#242] opened 2021-10-13 02:37 UTC
Hi!
i cant install daisyui on my mac.

`20 verbose Darwin 20.6.0
21 verbose argv "/opt/homebrew/Cellar/node@14/14.18.1/bin/node" "/opt/homebrew/opt/node@14/bin/npm" "i" "daisyui"
22 verbose node v14.18.1
23 verbose npm  v6.14.15
24 error Unexpected token , in JSON at position 693246 while parsing near '...0"
24 error         }
24 error     }
24 error },
24 error "dependencies": {
24 error ...'
25 verbose exit [ 1, true ]
`

**Comment by saadeghi** [comment] 2021-10-17 21:47
I'm closing this because I could't reproduce the error.  
If anyone has a similar problem, feel free to re-open this issue with more info.

**Closed by saadeghi** 2021-10-17 21:47 UTC

**Comment by mohitRana-04** [comment] 2022-02-23 12:56
same error me too. I too cant able to install daisyui

**Comment by saadeghi** [comment] 2022-02-23 16:59
I don't know. Maybe there's a problem with your Node installation. The error message doesn't specify what's the problem so I would try reinstalling Node JS to see if that fixes the problem.

**Comment by saadeghi** [comment] 2022-02-23 16:59
https://github.com/npm/npm/issues/14268#issuecomment-254044072
