### ISSUE TITLE
Colors not correctly auto-installed for Windicss

### ISSUE THREAD

**Issue by marshallswain** [saadeghi/daisyui#197] opened 2021-09-14 05:17 UTC
The Daisy colors aren't getting auto-installed by calling `transform('daisyui')`.   As a workaround, I can do the following:

```ts
import daisyColors from 'daisyui/colors/index.js'

export default defineConfig({
   theme: {
      extend: {
         colors: {
            ...daisyColors
         }
      }
   }
})
```

Note that I don't have o install the `colors/windi` file to get the colors to work.

I've tried to debug what's going on.  I was able to verify that the `isTailwindInstalled !== false` code  at the bottom of index.js runs.  I couldn't do any further debugging tonight.

**Comment by saadeghi** [comment] 2021-09-17 15:00
Thanks for the workaround @marshallswain 👍  
Honestly Windi has been a huge problem for me. Their `transform ` API is super-buggy and never works as intended to transform plugins 🥲  I'm so tired of opening new issues there...  

If this workaround does the job, I can replace this in daisyUI docs 🤷‍♂️

**Comment by marshallswain** [comment] 2021-09-18 05:26
This has been my experience as well.  Their plug-in API is great, but is buggy when transforming tailwind-intended plugins.

I intend to explore the components more this weekend to see what doesn't work, but initial support is looking good with this workaround.

**Comment by saadeghi** [comment] 2022-01-17 08:57
I would suggest using Tailwind 3 instead. It's faster and JIT mode is enabled by default. 
I think I should close this because Windi's transform function is not behaving as expected and I can't do anything about it 🤷‍♂️

**Closed by saadeghi** 2022-01-17 08:57 UTC
