### ISSUE TITLE
How to use own hex color for checkbox?

### ISSUE THREAD

**Issue by Mashiane** [saadeghi/daisyui#1286] opened 2022-10-28 01:24 UTC
Hi there

I am able to set the toggle color as per previous solution provided.

Can you please advise if I can do same for checkbox?

Thanks a lot.

**Comment by saadeghi** [comment] 2022-10-29 12:59
duplicate of #1119  
You can also do this using class names (the 3 number values are HSL color values):
```html
<input
  type="checkbox"
  class="checkbox [--chkbg:0_0%_0%] [--chkfg:50_100%_50%]"
>
```

**Closed by saadeghi** 2022-10-29 12:59 UTC

**Comment by Mashiane** [comment] 2022-10-30 01:45
Thank you so much.

Also found some snippets of how to get hsl from hex,https://css-tricks.com/converting-color-spaces-in-javascript/

perfect.

**Comment by Mashiane** [comment] 2022-10-30 08:33
Hi

Can you please advise on how to then change the border color.

Please see this TPlay, Id like the first two to look as nice as the 3rd checkbox.

Thanks again, this is awesome:

https://play.tailwindcss.com/iVBF2KY5Rk

**Comment by saadeghi** [comment] 2022-10-30 12:20
Sure.  
You can use the same HSL value of `--chkbg` for the border like this: `border-[hsl(118_18%_66%)]`  
https://play.tailwindcss.com/5iaSB2Pc2y

**Comment by Mashiane** [comment] 2022-10-30 14:31
Thank you so much.
