### ISSUE TITLE
Build error using Pheonix and TailwindCSS: "SassError: Function hsla is missing argument $saturation."

### ISSUE THREAD

**Issue by ehaughee** [saadeghi/daisyui#206] opened 2021-09-18 00:47 UTC
I am trying to use DaisyUI with TailwindCSS and the Elixir web framework, [Phoenix](https://phoenixframework.org/).  I followed [this guide](https://experimentingwithcode.com/using-tailwind-in-phoenix/) to setup TailwindCSS in my application.  TailwindCSS is working fine.  However, when I add `daisyui` to the plugins, I receive the following error.  I assume I'm doing something wrong but hell if I know what it is.  Any help is appreciated and please let me know if this is better posted in a different forum/channel/etc.

### Error message
I receive the following error message on build
```text
Hash: 4a4719b99da3fd3dbf41
Version: webpack 4.46.0
Time: 16515ms
Built at: 09/17/2021 5:32:26 PM
                Asset       Size  Chunks             Chunk Names
       ../favicon.ico   1.23 KiB          [emitted]
../images/phoenix.png   13.6 KiB          [emitted]
        ../robots.txt  202 bytes          [emitted]
               app.js   14.6 KiB     app  [emitted]  app
Entrypoint app = app.js
[0] multi ./js/app.js 28 bytes {app} [built]
[./css/app.css] 1.24 KiB {app} [built] [failed] [1 error]
    + 2 hidden modules

ERROR in ./css/app.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Function hsla is missing argument $saturation.
        on line 579 of /Users/Eric/Projects/steamgamelistv2/assets/css/app.css
>>   background-color: hsla(var(--b1)/var(--tw-bg-opacity,1));

   --------------------^

    at /Users/Eric/Projects/steamgamelistv2/assets/node_modules/webpack/lib/NormalModule.js:316:20
    at /Users/Eric/Projects/steamgamelistv2/assets/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/Eric/Projects/steamgamelistv2/assets/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/Eric/Projects/steamgamelistv2/assets/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.callback (/Users/Eric/Projects/steamgamelistv2/assets/node_modules/sass-loader/dist/index.js:73:7)
    at Object.done [as callback] (/Users/Eric/Projects/steamgamelistv2/assets/node_modules/neo-async/async.js:8069:18)
    at options.error (/Users/Eric/Projects/steamgamelistv2/assets/node_modules/node-sass/lib/index.js:294:32)
 @ ./js/app.js 4:0-24
 @ multi ./js/app.js
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/sass-loader/dist/cjs.js!node_modules/postcss-loader/dist/cjs.js!css/app.css:
    Entrypoint mini-css-extract-plugin = *
    [./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./node_modules/postcss-loader/dist/cjs.js!./css/app.css] 319 bytes {mini-css-extract-plugin} [built] [failed] [1 error]

    ERROR in ./css/app.css (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./node_modules/postcss-loader/dist/cjs.js!./css/app.css)
    Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
    SassError: Function hsla is missing argument $saturation.
            on line 579 of /Users/Eric/Projects/steamgamelistv2/assets/css/app.css
    >>   background-color: hsla(var(--b1)/var(--tw-bg-opacity,1));

       --------------------^
```

### Versions
tailwindcss@2.2.9
daisyui@1.14.0

### File contents
`tailwind.config.js`
```javascript
module.exports = {
  purge: [
    "../**/*.html.eex",
    "../**/*.html.leex",
    "../**/views/**/*.ex",
    "../**/live/**/*.ex",
    "./js/**/*.js"
  ],
  darkMode: "class", // or 'media' or 'class'
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [
    require('daisyui'),
  ],
}

```

`app.css`
```scss
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";
```
`postcss.config.js`
```javascript
module.exports = {
  plugins: {
    "postcss-import": {},
    tailwindcss: {},
    autoprefixer: {}
  }
}
```

`webpack.config.js`
```javascript
const path = require('path');
const glob = require('glob');
const HardSourceWebpackPlugin = require('hard-source-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const TerserPlugin = require('terser-webpack-plugin');
const OptimizeCSSAssetsPlugin = require('optimize-css-assets-webpack-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin');

module.exports = (env, options) => {
  const devMode = options.mode !== 'production';

  return {
    optimization: {
      minimizer: [
        new TerserPlugin({ cache: true, parallel: true, sourceMap: devMode }),
        new OptimizeCSSAssetsPlugin({})
      ]
    },
    entry: {
      'app': glob.sync('./vendor/**/*.js').concat(['./js/app.js'])
    },
    output: {
      filename: '[name].js',
      path: path.resolve(__dirname, '../priv/static/js'),
      publicPath: '/js/'
    },
    devtool: devMode ? 'eval-cheap-module-source-map' : undefined,
    module: {
      rules: [
        {
          test: /\.js$/,
          exclude: /node_modules/,
          use: {
            loader: 'babel-loader'
          }
        },
        {
          test: /\.[s]?css$/,
          use: [
            MiniCssExtractPlugin.loader,
            'css-loader',
            'sass-loader',
            'postcss-loader',
          ],
        }
      ]
    },
    plugins: [
      new MiniCssExtractPlugin({ filename: '../css/app.css' }),
      new CopyWebpackPlugin([{ from: 'static/', to: '../' }])
    ]
    .concat(devMode ? [new HardSourceWebpackPlugin()] : [])
  }
};

```

**Comment by saadeghi** [comment] 2021-09-18 04:39
@ehaughee this `hsla(var(--b1)/var(--tw-bg-opacity,1))` is valid CSS and Sass should not have problems with that 🤔  
Can you try webpack's `style-loader` instead of sass loader? Because I don't think Sass is needed when there's Postcss [This webpack config](https://github.com/saadeghi/daisyui/blob/master/examples/webpack-postcss/webpack.config.js) may help

**Comment by ehaughee** [comment] 2021-09-18 20:06
@saadeghi Thanks for the quick reply.  I changed my Webpack CSS module to match that of the linked `webpack.config.js` and removed MiniCssExtractPlugin and then I got this error:

```text
ERROR in ./css/app.css
Module build failed (from ./node_modules/style-loader/dist/cjs.js):
TypeError: this.getOptions is not a function
    at Object.loader (/Users/Eric/Projects/steamgamelistv2/assets/node_modules/style-loader/dist/index.js:19:24)
 @ ./js/app.js 4:0-24
 @ multi ./js/app.js
```

After looking around on StackOverflow for a bit, I saw a suggestion to downgrade`style-loader` to 2.x so I did that and now have no build issues.  However, the DaisyUI styles don't seem to be getting imported (note no DaisyUI styles on the `textarea`):
<img width="1284" alt="image" src="https://user-images.githubusercontent.com/312189/133907208-87c2cf69-3b1f-4417-a895-621c766d5187.png">

I've also tried searching the bundled `app.css` for DaisyUI classes like `btn` or `textarea-bordered` but don't see anything.

FYI, the code (pre DaisyUI) is here on GitHub: https://github.com/ehaughee/steamgameslist/tree/v2

**Comment by saadeghi** [comment] 2021-09-19 12:12
@ehaughee I couldn't run your project because there are some ignored local dependencies.  
Can you please make an isolated example repo so I can reproduce this issue?

**Comment by saadeghi** [comment] 2021-09-23 22:29
I'm closing this for now. Feel free to reopen it with a link to an isolated example repo so I can reproduce this.

**Closed by saadeghi** 2021-09-23 22:29 UTC

**Comment by ehaughee** [comment] 2021-09-27 23:45
I think the only ignored local deps are Elixir and Erlang which I can't represent as part of the deps as they're compilers/VMs.  I'm fine with leaving this closed for now until I can do some more digging though.

**Comment by saadeghi** [comment] 2021-09-27 23:50
I'd be happy to help, but I don't think this is a bug from daisyUI.  
Because daisyUI is essentially a collection of CSS styles being added to Tailwind CSS 🤷‍♂️

**Comment by ehaughee** [comment] 2021-11-16 17:37
FYI, I upgraded to Phoenix 1.6 (which switches from Webpack to esbuild) and I ran into no issues.

**Comment by saadeghi** [comment] 2021-11-16 17:47
Great 👍  
Thanks for the update
