### ISSUE TITLE
Range component display broken on mobile

### ISSUE THREAD

**Issue by ddahan** [saadeghi/daisyui#1420] opened 2022-12-07 20:49 UTC
As you can see on the screenshot below, range components have the left side not rounded.
Tested with latest Safari and Brave (Chrome). Thanks!

![1524ACC5-7C3F-4076-B487-DC071D22A3C2_1_102_o](https://user-images.githubusercontent.com/1933516/206292231-e0aa9be7-14a4-4788-8cdd-5f598a15c4a6.jpeg)

**Comment by phil-schmidtke** [comment] 2022-12-09 20:32
I think it's already fixed, for me in version 2.43.0 it works completely fine. Maybe check it out with that version and see if it works for you.

**Comment by ddahan** [comment] 2022-12-09 23:24
No, this is not fixed with 2.43.0

![IMG_2705C1C46239-1](https://user-images.githubusercontent.com/1933516/206811189-e044acf7-d92f-4fcb-ae13-506bf4de8deb.jpeg)

**Comment by bryndsey** [comment] 2023-04-13 20:22
Based on a [similar issue](https://github.com/saadeghi/daisyui/issues/1105) that was posted earlier, it sounds like it might be an issue with Safari/Webkit. 

As far as dealing with it in your own code, in the thread of the issue I linked, you can find a [workaround](https://github.com/saadeghi/daisyui/issues/1105#issuecomment-1297415994) for using it in your own code which seems to involve setting the position of the preceding element to `relative`. It seemed to work around in the issue in my case.

**Comment by saadeghi** [comment] 2023-04-13 20:37
@bryndsey thank you.  
Yes it's a bug from the browser indeed and I really can't fix it on my own.  You can use the workaround tho.  
I hope they fix it soon.

Closing as a duplicate of https://github.com/saadeghi/daisyui/issues/1105

**Closed by saadeghi** 2023-04-13 20:37 UTC
