### ISSUE TITLE
Disable the initial page load button animation

### ISSUE THREAD

**Issue by jenishStudent** [saadeghi/daisyui#108] opened 2021-07-13 18:28 UTC
whenever my page loads the button animation is kicked in is there a way to disable this effect?

web.findoffer.com , if you look at the top navigation button

**Comment by saadeghi** [comment] 2021-07-13 19:19
I see that you already used `no-animation` class, so there wont be animations.

There are 2 ways to disable or change the animation:  
- using `no-animation` class to disable animation [[docs](https://daisyui.com/components/button/)]
- changing `--animation-btn` variable on theme which is `0.25s` by default [[docs](https://daisyui.com/docs/add-themes)]
- adding some custom CSS : `.btn {animation: none;}`

Please let me know if you have any questions

**Comment by jenishStudent** [comment] 2021-07-13 20:21
do you know why its animating then even if i am using no-animation class?

**Comment by saadeghi** [comment] 2021-07-13 21:24
@jenishStudent It should have animation. What version of browser are you using?

**Comment by saadeghi** [comment] 2021-07-19 06:51
I'm closing this because I couldn't reproduce. Feel free to reopen this issue with more information if the problem still exists.

**Closed by saadeghi** 2021-07-19 06:51 UTC

**Comment by AndaHendriksen** [comment] 2024-03-21 08:46
I have the same problem. I want animations on the button, just not on the initial page load. If you go to [daisyui.com/components/button/](https://daisyui.com/components/button/), all the buttons animate on page load.

**Comment by Rkaede** [comment] 2024-07-01 05:39
To stop the animations on page load, add the following to a global css file:

```css
.btn {
  @media (prefers-reduced-motion: no-preference) {
    animation: none;
  }
}
```
