### ISSUE TITLE
Tailwind 3 support?

### ISSUE THREAD

**Issue by zenhorace** [saadeghi/daisyui#328] opened 2021-12-10 17:04 UTC
Tailwind 3 is out now. Is there any work that needs to be done to support DaisyUI as it relates to breaking changes?

**Comment by zenhorace** [comment] 2021-12-10 17:10
it does appear there are breaking changes #329

**Comment by saadeghi** [comment] 2021-12-10 17:32
I'm closing this as a duplicate of #327,  
Let's discuss your case here on #329

**Closed by saadeghi** 2021-12-10 17:32 UTC
