### ISSUE TITLE
bug: [React] dropdown - after dismissing dialog opened from dropdown, focus is returned to label element, reopening dropdown

### ISSUE THREAD

**Issue by r3wt** [saadeghi/daisyui#2425] opened 2023-10-18 16:02 UTC
### What version of daisyUI are you using?

3.9.3

### Which browsers are you seeing the problem on?

Firefox

### Reproduction URL

https://play.tailwindcss.com/JGN0l5uIdN

### Describe your issue

I attempted to reproduce it in the link above, but it doesn't work. perhaps it is something specific react is doing under the hood for `tabIndex`/ `focus`? i have checked and neither component is rerendered, so its just a head scratcher.

**Comment by r3wt** [comment] 2023-10-18 16:19
interestingly, i was able to fix it by switching from `a` to `button` for the dropdown items. i think it is the presence of a with empty href which is causing the focus to return when dismissing the dialog.

**Comment by saadeghi** [comment] 2023-10-20 06:51
The code works as expected:  
https://stackblitz.com/edit/daisyui-nextjs-22ximc/?file=pages%2Findex.js

I just removed that `e.preventDefault()` and changed `onclick` to JSX syntax.

So I think the issue is somewhere else. daisyUI is just CSS style so I'm going to close this issue but feel free to continue the conversation. Let me know if I can help.

**Closed by saadeghi** 2023-10-20 06:51 UTC
