### ISSUE TITLE
bug: menu break in NextJs production build

### ISSUE THREAD

**Issue by technophile-04** [saadeghi/daisyui#2303] opened 2023-08-29 06:25 UTC
### What version of daisyUI are you using?

^3.0.2

### Description : 
When running locally `menu` link item has the following CSS rules applied : 
![Screenshot 2023-08-29 at 2 21 10 AM](https://github.com/saadeghi/daisyui/assets/80153681/85230cea-f205-46b1-bd7f-76cb3c7e41dc)

 But when once you `build` and serve it the above CSS rules are not added to menu link item 
 
 
### Reproduction steps : 
1. Open https://stackblitz.com/edit/daisyui-nextjs-lzc8vy : This is minimal reproduction repo forked from daisyUI nextjs template and I have just copied [`menu with icons & badge`](https://daisyui.com/components/menu/#menu-with-icons-and-badge-responsive)

2. Terminate process in terminal and build the app -> `npm run build`

3. Serve the exported build -> `npm run start`

You will the menu item are broken vertical instead of being horizontal : 

![Screenshot 2023-08-29 at 11 50 37 AM](https://github.com/saadeghi/daisyui/assets/80153681/c04cef3a-2277-4bfc-8c78-997e68cbdf47)

### Notes : 

This also breaks in Next version `^13.1.5` here is the repo link to test it out : https://github.com/scaffold-eth/scaffold-eth-2

### Some references discussion : 
1 . https://github.com/saadeghi/daisyui/discussions/2272

2 . https://github.com/saadeghi/daisyui/discussions/2183

### What browsers are you seeing the problem on?

All browsers

### Reproduction URL

https://stackblitz.com/edit/daisyui-nextjs-lzc8vy

**Comment by saadeghi** [comment] 2023-08-30 09:16
Update Next.js to the latest version.  
It was a CSS processing bug in Next.js but it's fixed now.

**Closed by saadeghi** 2023-08-30 09:16 UTC

**Comment by wuarmin** [comment] 2023-10-16 10:57
@saadeghi I have a similar issue in a create-react-app production build:

Menu in dev:
![image](https://github.com/saadeghi/daisyui/assets/9987680/2286a6f0-13db-4bc3-8c3b-1b7bf195dfa6)

Menu in prod:
![image](https://github.com/saadeghi/daisyui/assets/9987680/9a21c6c3-a66d-4445-b87c-9c9916a4868b)

What can I do?
Thanks!

**Comment by saadeghi** [comment] 2023-10-16 11:30
@wuarmin can you update all the dependencies (especially the ones about build tool or CSS processing)?  
Because it's not an issue from daisyUI, it was a bug from CSS build tool which must be fixed by the latest version.

If it didn't help, please share a reproduction repo.

**Comment by wuarmin** [comment] 2023-10-16 14:42
@saadeghi Thanks! An upgrade helped. I don't know which package caused the error.
