### ISSUE TITLE
bug: dropdown items not visible

### ISSUE THREAD

**Issue by vfilatov** [saadeghi/daisyui#1997] opened 2023-06-13 17:56 UTC
### What version of daisyUI are you using?

v3.1.0

### Describe your issue

Click on "btn 1"
"Item 1" not visible as covered by "btn 2"
```html
    <div class="dropdown">
      <label tabindex="0" class="btn m-1">btn 1</label>
      <ul tabindex="0" class="dropdown-content menu p-2 shadow bg-base-100 rounded-box w-52">
        <li><a>Item 1</a></li>
        <li><a>Item 2</a></li>
      </ul>
    </div>
    <br />
    <div class="dropdown">
      <label tabindex="0" class="btn m-1">btn 2</label>
      <ul tabindex="0" class="dropdown-content menu p-2 shadow bg-base-100 rounded-box w-52">
        <li><a>Item 1</a></li>
        <li><a>Item 2</a></li>
      </ul>
    </div>
```

### What browsers are you seeing the problem on?

Chrome, Firefox

**Comment by saadeghi** [comment] 2023-06-14 05:45
Duplicate of https://github.com/saadeghi/daisyui/issues/1948#issuecomment-1581632158

**Closed by saadeghi** 2023-06-14 05:45 UTC
