### ISSUE TITLE
bug: Loading spinner on Safari

### ISSUE THREAD

**Issue by robsontenorio** [saadeghi/daisyui#2570] opened 2023-11-23 19:23 UTC
### What version of daisyUI are you using?

4.4.4

### Which browsers are you seeing the problem on?

Safari, Safari iOS

### Reproduction URL

there is no ...

### Describe your issue

Just notice on **builded version** this issue happens (`yarn build`). 

- Simple refresh freezes (cmd+R)
- Hard refresh works (option+cmd+R)
- Then, a simple refresh again make it freezes.

But **not happens with dev version** with `yarn dev`.

**Am I missing something?**

https://github.com/saadeghi/daisyui/assets/118955/a497469d-1642-4445-8016-2839c83d82a5

**Comment by robsontenorio** [comment] 2023-11-23 21:26
I can reproduce it on daisyUI site.

- Simple refresh: spinner stops
- Then I did hard refresh (option+cmd+R) then it works again.


https://github.com/saadeghi/daisyui/assets/118955/3e0eb417-bf1e-4805-857d-a67740e53f72

**Comment by saadeghi** [comment] 2023-11-23 23:18
Interesting…

That's definitely a Safari bug. I tried to see if changing the order of CSS rules (`mask-image` and `-webkit-mask-image`) would make it work but the bug still happened. The problem is the CSS animation inside the SVG. It is expected to work and we can't extract that animation out of the SVG because daisyUI can't manually put a SVG inside the HTML and animate it. The SVG has to be inside the CSS mask and the animation has to be inside the SVG.  

I will research more to find a way for it.  
As a temporary workaround and to prevent this bug to break Mary, looks like adding the `loading` class names after render prevents the bug?

**Comment by robsontenorio** [comment] 2023-11-24 00:03
@saadeghi Yes I tried it. But, bug remains even if I inject class on client side.

```html
<span class="<inject 'loading' here after render>  loading-spinner loading-xs"></span>
```

**Comment by saadeghi** [comment] 2023-11-24 00:04
what if you inject both `loading` and `loading-spinner`?

**Comment by robsontenorio** [comment] 2023-11-24 00:14
@saadeghi  Same issue. Here is a snippet

1) Simple refresh: bug
2) Hard refresh: works
3) Simple refresh again: bug

```html
<span id="spin" class=""></span>
<button onclick="document.getElementById('spin').classList.add('loading', 'loading-spinner')">run</button>
```

**Comment by denis23kw** [comment] 2023-11-26 07:08
The same issue!

Mac Pro M1, Safari Version 16.5.2, DaisyUI 4.4.2

**Comment by robsontenorio** [comment] 2023-12-11 01:17
@saadeghi 

Can we consider this is definitely a Safari bug without any workarounds for now ?

**Comment by saadeghi** [comment] 2023-12-11 01:25
It is a Safari bug. I hope it gets fixed in the next Safari update 🤞  
A workaround would be using SVG [`<animate>` tag](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/animate) for animations instead of CSS animation but it's not easy to replicate the exact same CSS animation with that 🫣

**Comment by OptimusCrime** [comment] 2024-06-08 14:49
I can confirm that this is still a problem today. The spinner:

```
        <span className="loading loading-spinner loading-lg"></span>
```

Does not animate at all in Safari (both desktop and on iOS), and just the first bit of the loading icon is rendered. What is weird is that the animations works as expected in the docs page at https://daisyui.com/components/loading/ . Does anyone know why this is happening?

**Comment by scosman** [comment] 2024-11-14 17:28
A simple workaround is:

```
.loading-spinner {
  mask-image: url("/images/spinner.svg");
}
```

Where the image is: https://github.com/n3r4zzurr0/svg-spinners/blob/main/svg-css/ring-resize.svg

I'm not sure if the SVG does something different, or if the url instead of inline fixes it. Either way it works.

**Comment by robsontenorio** [comment] 2024-11-14 17:30
@scosman In my case unfortunately I can't use this workaround.

**Comment by scosman** [comment] 2024-12-09 00:16
Over a year later maybe worth a library level patch? Safari team doesn't seem to think this is a priority.

@saadeghi ?

**Comment by saadeghi** [comment] 2024-12-09 01:43
@scosman Yes! For daisyUI 5 loading animations will be using svg animations instead of inline CSS animation inside a encoded svg, which fixes the issue. I will add a patch soon to fix it in daisyUI 4 as well

**Closed** 2024-12-09 02:19 UTC
Labels: v5
