### ISSUE TITLE
WindiCSS - Buttons missing hover styles

### ISSUE THREAD

**Issue by cnb-philip** [saadeghi/daisyui#114] opened 2021-07-30 13:45 UTC
This problem is present in the windi-cli example.  Hovering over the primary/secondary buttons do not change the background to the appropriate color.  It just uses just the default button hover background color.  Upon inspecting the generated output.css, it appears the classes `.btn-primary.btn-active,.btn-primary:hover` are not being generated. 

Buttons were the first and only thing I tested, so there could be other instances of classes not being generated in other components.

**Comment by saadeghi** [comment] 2021-07-30 15:20
I think that's a bug on Windi CSS and I'm afraid I can't do anything about it on my side.  
https://github.com/windicss/windicss/issues/345
If you're to using Windi CSS, you can add `hover:` classes to rewrite the colors until there is a fix for that.
```html
<button class="btn btn-primary hover:bg-primary-focus hover:border-primary-focus">button</button>
<button class="btn btn-secondary hover:bg-secondary-focus hover:border-secondary-focus">button</button>
<button class="btn btn-accent hover:bg-accent-focus hover:border-accent-focus">button</button>
```

I'm closing this issue because it's not a bug on daisyUI. Please follow [the linked issue](https://github.com/windicss/windicss/issues/345) to get notified when it's fixed.

**Closed by saadeghi** 2021-07-30 15:20 UTC
