### ISSUE TITLE
bug: daisyui doesn't compile with nextjs 15

### ISSUE THREAD

**Issue by luluhoc** [saadeghi/daisyui#3319] opened 2024-12-15 00:56 UTC
### What version of daisyUI are you using?

v4.12.22

### Which browsers are you seeing the problem on?

All browsers

### Reproduction URL

none

### Describe your issue

```
Parsing css source code failed
  1298 |   }
  1299 |
> 1300 |    {
       |     ^
  1301 |     grid-auto-flow: row dense !important;
  1302 |   }
  1303 |

Invalid empty selector at [project]/src/styles/globals.css:1299:4
```

**Comment by saadeghi** [comment] 2024-12-15 00:57
Reproduction URL please

**Comment by bathtaters** [comment] 2024-12-16 02:11
I've noticed that Turbopack, which Next.JS uses in v15 over Webpack to compile the 'dev' server (i.e. npm run dev), will not compile if it detects any invalid CSS.

This helped me locate and fix some probably bad practices I was using (In my case combining tailwind and daisyUI classes that weren't intended to be combined). [See Next.JS Turbopack](https://nextjs.org/docs/app/api-reference/turbopack) for more info.

But to quickly fix the issue, I was able to just remove `--turbopack` from my package.json (Under scripts.dev) to use Webpack instead.

**Comment by saadeghi** [comment] 2024-12-16 02:18
What was the problematic style?

**Comment by saadeghi** [comment] 2024-12-16 02:34
> .file\:btn[disabled]::file-selector-button,.file\:btn::file-selector-button:disabled

😅🙈

I guess we can close this issue then. 

Good news is, starting with daisyUI 5 (coming soon) it will be possible to include or exclude every part of library and it give us more control. Or would be also beneficial for projects with existing styles to incrementally use daisyUI without getting conflicts from existing styles.

**Closed by saadeghi** 2024-12-16 02:34 UTC
