### ISSUE TITLE
[modal] - Make overlay full height 

### ISSUE THREAD

**Issue by workingxx92** [saadeghi/daisyui#136] opened 2021-08-16 16:08 UTC
<img width="1126" alt="Screen Shot 2021-08-16 at 11 05 54 PM" src="https://user-images.githubusercontent.com/86577210/129594548-3690941b-c139-4b18-a74b-44854d598fc2.png">

**Comment by saadeghi** [comment] 2021-08-16 16:27
@workingxx92 
On daisyUI site I had to put the modal nested inside the page content because of my components structure. I should fix that, but I must stress that it's not a problem with the component itself. It's a problem with the demo site.  

This won't happen if you put the `modal` after the page content (for example before`</body>`)  

This is also a common practice for all other modal components because a modal is a new layer outside of the current page. If it gets nested, it just fills the first relative parent. So, it's better to put it before the`</body>` tag.

**Comment by workingxx92** [comment] 2021-08-17 00:34
Hi.
I tried. It not woking in Vuejs

**Comment by saadeghi** [comment] 2021-08-17 01:34
@workingxx92 Here's [a Vue project](https://github.com/saadeghi/vuejs-daisyui-modal) and it works fine

**Comment by workingxx92** [comment] 2021-08-17 02:58
I think the issue is related to the scrolling bar. How to fix it

**Comment by saadeghi** [comment] 2021-08-17 08:48
@workingxx92 what's is the issue with scrollbar exactly? Because I don't see any issues 👀

**Comment by saadeghi** [comment] 2021-08-20 12:40
I'm closing this. Feel free to reopen again with more information provided.

**Closed by saadeghi** 2021-08-20 12:40 UTC
Labels: documentation

**Comment by saadeghi** [comment] 2021-08-23 13:34
@workingxx92 There should't be a problem if you put the modal after the page content.
```html
<body>

  <main>
    <div>
      <label for="my-modal-1" class="btn btn-primary modal-button">open modal</label> 
      <!-- page content -->
    <div>
  </main>

  <!-- modal content -->
  <input type="checkbox" id="my-modal-1" class="modal-toggle"> 
  <div class="modal">
    <div class="modal-box">
      <p>modal text</p> 
      <div class="modal-action">
        <label for="my-modal-1" class="btn">Close</label>
      </div>
    </div>
  </div>

</body>
```
If there is still a problem, I need you to make a small example repo on Github so I can reproduce the issue.

**Comment by workingxx92** [comment] 2021-08-23 14:01
HI. I don't put the modal after the page content.

**Comment by workingxx92** [comment] 2021-08-23 15:55
@saadeghi 
Please make a modal component that doesn't need put code modal after the page content (before</body>)
