### ISSUE TITLE
Antialiasing

### ISSUE THREAD

**Issue by filipot** [saadeghi/daisyui#123] opened 2021-08-07 23:45 UTC
You probably already know about this, but there seems to be some problem with antialiasing, making the checkbox look like its bitten off:
![antialiasing](https://user-images.githubusercontent.com/3662005/128616371-6b8f798a-2436-4517-986c-31c023d572ae.png)
Sometimes it looks really ugly due to that.
Running on an 1080p screen.

Btw loving Daisyui! It looks smooth :D, good job!

**Comment by saadeghi** [comment] 2022-01-23 19:52
I'm closing this as a duplicate of #427 because #427 has a better description on the problem. Follow that to get updates.

**Closed by saadeghi** 2022-01-23 19:52 UTC
Labels: enhancement
