### ISSUE TITLE
bug: Drawer scrollbar will not be hidden in Firefox

### ISSUE THREAD

**Issue by J4gQBqqR** [saadeghi/daisyui#2782] opened 2024-01-22 15:31 UTC
### What version of daisyUI are you using?

4.6.0

### Which browsers are you seeing the problem on?

Firefox

### Reproduction URL

https://daisyui.com/components/drawer/

### Describe your issue

When Drawer is hidden in Firefox, the scrollbar for the Drawer sidebar will not hide itself. Instead, it will appear as it is and unable to scroll or drag using mouse.

![image](https://github.com/saadeghi/daisyui/assets/77554817/d3143987-8da6-4597-8c55-aaa3d937340d)

**Comment by naegelin** [comment] 2024-02-08 17:22
Is this a duplicate of #991 ?

**Comment by J4gQBqqR** [comment] 2024-02-08 17:38
Not sure. 

This is drawer on the left side and following exactly the daisyui documentation. The official documentation website is showing double scroll bar in Firefox when drawer is not shown.

**Comment by J4gQBqqR** [comment] 2024-02-08 17:40
Could this be a bug of Firefox?

**Closed** 2024-02-12 20:50 UTC
