### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by lautarocolazo** [saadeghi/daisyui#2519] opened 2023-11-14 04:00 UTC
### What version of daisyUI are you using?

v4.0.4

### Which browsers are you seeing the problem on?

Firefox

### Reproduction URL

daisyui.com

### Describe your issue

Hello! 
I read about the new Theme Controller component and I wanted to try it! When I was on the Daisy UI website, I noticed that in the interactive themes dropdown all of the themes had the same colors and when I clicked on different ones the website was not changing. Anyway, I went ahead and updated my project to the latest version (4.0.4) and copied and pasted one of the theme controller components just to run a quick test. After updating to the latest version, the theme of my project was the default "dark" theme, and the toggle button did not change anything. I went ahead and tried opening the project in Chrome and it's working perfectly. It's just Firefox where it's broken. 

I am running version 4.0.4 of Daisy and I am running the 119.0 Firefox version. The only two add-ons that I have in my browser are Bitwarden and DuckDuckGo, so I don't think that any of that is causing the issue.
Also, since the exact same code is working ok in Chrome I have no idea how to replicate the issue. Maybe I am not experienced enough, sorry for that.

I couldn't find an issue related to this. 

Is this an issue that is happening just to me?

**Comment by alexzvn** [comment] 2023-11-14 04:10
I believe you have same issue with #2503 due to firefox version bellow 121 doesn't support `:has()` selector.

**Comment by lautarocolazo** [comment] 2023-11-14 04:15
Thank you so much @alexzvn ! I promise that I tried to look for another similar issue and didn't find it haha. I will take a look and update if I was able to fix it!

**Comment by saadeghi** [comment] 2023-11-14 04:58
Duplicate of #2503  
Let's discuss there

**Closed by saadeghi** 2023-11-14 04:58 UTC
