### ISSUE TITLE
Click on Dropdown button does not close it

### ISSUE THREAD

**Issue by Lozoute** [saadeghi/daisyui#589] opened 2022-03-14 10:48 UTC
Hi, first I wanna say that I really love all the work! It's amazing!

I wanna make a suggestion, quand using a Dropdown, a click on the button (or associated label, whatever) will open the Dropdown component but if we click again it will not close. So to close it we have to click outside. Can we add a class or something so it can also close when the user click on the button again? I think most user will have the reflex to click on the button again.

**Comment by saadeghi** [comment] 2022-03-14 11:07
Duplicate of #157

**Closed by saadeghi** 2022-03-14 11:07 UTC
