### ISSUE TITLE
Buttons (and maybe other components) are still colored when hovered but disabled

### ISSUE THREAD

**Issue by Acccent** [saadeghi/daisyui#655] opened 2022-03-25 20:56 UTC
Hi,

It looks like [the styling for hovered/active buttons](https://github.com/saadeghi/daisyui/blob/34ef78474af676a7c5e99738c1f6bf2601731c7a/src/components/styled/button.css#L32) takes precedence over that of [disabled buttons](https://github.com/saadeghi/daisyui/blob/34ef78474af676a7c5e99738c1f6bf2601731c7a/src/components/styled/button.css#L188). Normally that shouldn't be a problem since disabled buttons have `pointer-events: none;` but I found that on mobile at least, when tapping on a button, that button retains its color even if it is now disabled (until unfocused).

There's a pretty simple fix (just add `:not(&-disabled):not([disabled])` for variants styling) and I would submit a pull request myself, but I don't know if you have a build file somewhere that generates this behaviour for all interactive elements.

**Comment by saadeghi** [comment] 2022-03-26 09:27
I can't reproduce this issue. 
Can you give me a code example of that disabled button (which has colors on mobile)?

Also, please mention your mobile OS and browser.

**Comment by saadeghi** [comment] 2022-03-27 13:57
I'm closing this.  
Please re-open after providing a code example.

**Comment by Acccent** [comment] 2022-03-27 23:46
You can try it out in the official documentation: https://daisyui.com/components/button/
If you open your inspector and manually toggle the "hover" state for the disabled buttons, you'll see that the button color changes. It's even more visible if the button has a variant class like `btn-primary` etc.

This isn't technically a mobile-only issue, it's just that tapping a button on mobile gives it the hover state, and it keeps it until you tap elsewhere, even if the button becomes disabled. I'm on Android 12, using Vivaldi 5.1 or Chrome 99.

**Comment by Acccent** [comment] 2022-03-27 23:49
(I can't re-open the issue myself.)

**Closed** 2022-03-28 07:55 UTC
