### ISSUE TITLE
Duplicated CSS issue using SvelteKit and daisyUI

### ISSUE THREAD

**Issue by atresnjo** [saadeghi/daisyui#48] opened 2021-05-21 13:54 UTC
Repo showcasing the [issue]( https://github.com/atresnjo/sveltekit-daisyui-issue)

The local dev build works fine, but the production build somehow messes up with the CSS. The weird thing is that the DevTools shows duplicates, even though there are no duplicates in the actual generated CSS file.

Asked also in Svelte discord, will report back once I know more. If anyone has an idea, feel free to share. :)

**Comment by atresnjo** [comment] 2021-05-21 14:21
I'm not too sure yet why this is happening, but here's a workaround:

1. Set "themes" to false in the tailwind config under "daisyui"
```json
	daisyui: {
		styled: true,
		themes: false,
		rtl: false
	}
```
2. Load the themes from the CDN
```html
<link href="https://cdn.jsdelivr.net/npm/daisyui@0.28.0/dist/themes.css" rel="stylesheet" type="text/css" />
```

I'll still leave this open in case we get an actual fix.

**Comment by saadeghi** [comment] 2021-05-21 15:23
Thanks for the repo link. I will try to reproduce it today. 
Havee you tried to build without cssnano? Because cssnano seems the only difference in your dev/prod build.

**Comment by atresnjo** [comment] 2021-05-21 16:42
Oh, it seems cssnano was causing it. Seems to work fine so far without cssnano. I'll play around more and report back.

**Comment by saadeghi** [comment] 2021-05-21 17:25
@atresnjo great!  
I think you can try a different cssnano config to workaround this issue. For example disabling `mergeRules` option on cssnano might help.  
I'm closing this issue but if you found more details about the cause of problem, I'd be glad to know.

**Closed by saadeghi** 2021-05-21 17:25 UTC
