### ISSUE TITLE
bug: Collapse Title bouncing when opened or closed (Collapse with checkbox)

### ISSUE THREAD

**Issue by Weltfremder** [saadeghi/daisyui#2406] opened 2023-10-12 06:14 UTC
### 1. What version of daisyUI are you using?

v3.5.0

### 2. Describe your issue

Using the collapse with checkbox element and restyle it with smaller padding top and bottom and no min-height on both title and input makes the title div grow bigger on click for a small duration but enough that it's visible.

### 3. What browsers are you seeing the problem on?

Chrome

### 4. Reproduction URL

https://daisyui.com/components/collapse/

**Comment by saadeghi** [comment] 2023-11-26 07:11
duplicate of #2137

**Closed** 2023-11-26 07:12 UTC
