### ISSUE TITLE
bug: Can't read the text when the menu active

### ISSUE THREAD

**Issue by Buzhifanji** [saadeghi/daisyui#2024] opened 2023-06-19 10:52 UTC
### What version of daisyUI are you using?

v3.1.1

### Describe your issue

![图片](https://github.com/saadeghi/daisyui/assets/28743253/33e7d19c-4762-4cf7-a023-90dbdfa7cc12)

![图片](https://github.com/saadeghi/daisyui/assets/28743253/d8bf5e9a-892d-45bd-8455-1c5da571ec67)

![图片](https://github.com/saadeghi/daisyui/assets/28743253/73aa9547-c420-47c0-8d90-93e017a146f4)

![图片](https://github.com/saadeghi/daisyui/assets/28743253/fb7f320c-51f2-47c8-ad50-486552678722)

![图片](https://github.com/saadeghi/daisyui/assets/28743253/3c8c6bc1-75c8-4bad-97af-27e55b9a5310)

and so on

### What browsers are you seeing the problem on?

Firefox, Edge

### Reproduction URL (optional)

https://daisyui.com/components/menu/

**Comment by DJ-caddev** [comment] 2023-06-19 14:38
Duplicate of https://github.com/saadeghi/daisyui/issues/2021

**Closed** 2023-06-20 22:26 UTC
