### ISSUE TITLE
Input text border is not rounded on iOS Safari

### ISSUE THREAD

**Issue by kodsu** [saadeghi/daisyui#1090] opened 2022-09-02 11:51 UTC
At first a though the problem was with my project but even on the official page it shows this behavior.

![image](https://user-images.githubusercontent.com/17864005/188135898-534ca466-4b17-4eef-be68-e6243bf566ee.jpeg)

iOS 15.5

**Comment by saadeghi** [comment] 2022-09-02 12:01
Duplicate of https://github.com/saadeghi/daisyui/issues/978

It's a Safari bug from 14 years ago 🤦‍♂️  
 https://bugs.webkit.org/show_bug.cgi?id=20807

**Closed by saadeghi** 2022-09-02 12:01 UTC

**Comment by kodsu** [comment] 2022-09-02 12:36
> Duplicate of https://github.com/saadeghi/daisyui/issues/978
> 
> 
> 
> It's a Safari bug from 14 years ago 🤦‍♂️  
> 
>  https://bugs.webkit.org/show_bug.cgi?id=20807

Oh okay thank you. I searched for a similar issue but didn't find this one.
