### ISSUE TITLE
bug: Console spam

### ISSUE THREAD

**Issue by ttijl** [saadeghi/daisyui#1792] opened 2023-05-03 08:34 UTC
### What version of daisyUI are you using?

2.51.6

### Describe your issue

In the console this message always appears 3 times. Really annoying when developing. Does this need to be 3 times and can i disable it somewhere
```

🌼 daisyUI components 2.51.6  https://daisyui.com
  ✔︎ Including:  base, components, 1 themes, utilities
  ❤︎ Support daisyUI:  https://opencollective.com/daisyui 
  
```

### What browsers are you seeing the problem on?

Other

**Comment by saadeghi** [comment] 2023-05-03 08:58
Duplicate of https://github.com/saadeghi/daisyui/issues/300

**Closed by saadeghi** 2023-05-03 08:58 UTC
