### ISSUE TITLE
Component - Dropdown  How does one close the dropdown

### ISSUE THREAD

**Issue by rhscjohn-dev** [saadeghi/daisyui#521] opened 2022-02-25 21:46 UTC
Version 2.2.1
On your web page, when you click on an item in the dropdown list, the dropdown disappears.

I am trying the dropdown component in SvelteKIt and after clicking on a item in the dropdown list,  the dropdown stays open.  How do I programmatically close the dropdown after I have processed the onClick event.

Pretty much just copied and pasted your first dropdown example into Svelte.

dropdown.svelte
```
<script>
  let itemClicked = "";

  //handle click event on dropdown
  const onClickDropdown = (event) => {
    console.log("onClickDropDown:", event.target.innerHTML);
    itemClicked = event.target.innerHTML;
  };
</script>

<svelte:head>
  <title>Dropdown</title>
</svelte:head>

<div class="m-4 text-xl font-semibold">Dropdown Menu</div>
<div class="dropdown">
  <label tabindex="0" for="dropdownMenu" class="m-1 btn">Click</label>
  <ul
    tabindex="0"
    class="p-2 shadow menu dropdown-content bg-base-100 rounded-box w-52"
  >
    <!-- svelte-ignore a11y-missing-attribute -->
    <li on:click={onClickDropdown}><a>Item 1</a></li>
    <!-- svelte-ignore a11y-missing-attribute -->
    <li on:click={onClickDropdown}><a>Item 2</a></li>
  </ul>
</div>
<pre>You clicked on: {itemClicked}</pre>
```
Is there a class I can add that will close the dropdown?   After I click on an item, I can click outside of the dropdown and the dropdown will close.  The escape key should also close the dropdown.

![Screenshot 2022-02-25 162909](https://user-images.githubusercontent.com/60523782/155807123-0e3aa6f5-a979-471f-a837-63b726d71e40.png)

**Comment by christianblandford** [comment] 2022-02-25 21:55
You have to unfocus/blur the menu to close it

**Comment by saadeghi** [comment] 2022-02-25 22:44
Duplicate of #201

**Closed by saadeghi** 2022-02-25 22:44 UTC
