### ISSUE TITLE
bug: accordian collapse content cuts off its content in docs (firefox)

### ISSUE THREAD

**Issue by AndreasPB** [saadeghi/daisyui#1894] opened 2023-06-02 07:40 UTC
### What version of daisyUI are you using?

3.0.0

### Describe your issue

Spotted in the docs

It's only an issue with Firefox - it looks fine when using Google Chome
I'm using Firefox version 109.0

![picture](https://github.com/saadeghi/daisyui/assets/43907402/cc614947-0398-49f9-90ee-e73d96fdd6ae)

### What browsers are you seeing the problem on?

Firefox

### Reproduction URL (optional)

https://daisyui.com/components/accordion/

**Comment by saadeghi** [comment] 2023-06-02 12:03
duplicate of #1883

**Closed by saadeghi** 2023-06-02 12:03 UTC
