### ISSUE TITLE
Css not rendering with jit mode enabled

### ISSUE THREAD

**Issue by iamshimer** [saadeghi/daisyui#223] opened 2021-10-04 09:36 UTC
I am trying to install daisyUI in a tailwind css project. But After i implemented that the styles of button are not rendering. After i removed "mode:"jit" line from tailwind config file. after that the styles rendered normally. Can't i use daisyUI with jit mode?. Because JIT is boosting the performance of my spp

**Comment by saadeghi** [comment] 2021-10-04 09:47
@iamshimer daisyUI works with JIT perfectly.  
Can you please create a example repo so I can reproduce this issue?

**Comment by iamshimer** [comment] 2021-10-04 10:10
https://github.com/iamshimer/my-next-tailwind

**Comment by saadeghi** [comment] 2021-10-04 10:47
@iamshimer I just cloned your repo, installed dependencies and `npm run dev`. It worked without any problem.  
It's weird that it's not working for you. the only problem I see is that you used `class` instead of `className` in a react project but I think Next.js handles that.

Anyway, can you try reinstalling npm or restarting your app to see if that helps? because I don't see any problem with your Tailwind setup.

**Comment by iamshimer** [comment] 2021-10-04 10:54
@saadeghi  okay i will check it once more

**Comment by saadeghi** [comment] 2021-10-05 02:49
I'm closing this because there seems to be no issues with JIT.

Feel free to reopen this issue if there's still a problem.

**Closed by saadeghi** 2021-10-05 02:49 UTC
