### ISSUE TITLE
bug: [WARNING] Unexpected "*" when building.

### ISSUE THREAD

**Issue by RomkaLTU** [saadeghi/daisyui#3055] opened 2024-05-25 19:10 UTC
### What version of daisyUI are you using?

v4.11.1

### Which browsers are you seeing the problem on?

All browsers

### Describe your issue

Getting warnings when building:

[WARNING] Unexpected "*" [css-syntax-error]
[WARNING] Unexpected "li" [css-syntax-error]

![CleanShot 2024-05-25 at 22 11 44](https://github.com/saadeghi/daisyui/assets/10167743/f601e047-51f0-4770-89c0-6556a3f8be8f)

Using Laravel, TailwindCSS, Livewire.

"daisyui": "^4.11.1"
"vite": "^5.2.11"
"laravel-vite-plugin": "^1.0.4"
"postcss": "^8.4.38"
"tailwindcss": "^3.4.3"

I beleave this is somehow related to dark mode selectors.
Can't provide reproduction URL at the moment.

**Comment by saadeghi** [comment] 2024-05-26 13:51
How are you using `dark` class name?  
FYI, dark class name is not from daisyUI and you don't need it anyway if you use daisyUI color names.

**Comment by RomkaLTU** [comment] 2024-05-27 07:07
I'm not actually use it, I just included 2 components into my project (no customizations), button and accordion that's it.

**Comment by saadeghi** [comment] 2024-05-27 13:42
`.dark` class name does not exist anywhere in daisyUI so I assume the code you're getting error about is coming from another source.

Feel free to continue the conversation. I'm closing this issue since the issue is not from daisyUI.

**Closed by saadeghi** 2024-05-27 13:42 UTC

**Comment by LucVK** [comment] 2024-05-30 07:26
I get the same errors when building a custom theme for filamentphp (laravel/livewire).
When removing the daisyui plugin from the tailwind config, the error messages disappear.
