### ISSUE TITLE
bug: Menu opens behind cards

### ISSUE THREAD

**Issue by mdochdev** [saadeghi/daisyui#2019] opened 2023-06-18 23:50 UTC
### What version of daisyUI are you using?

Since 3.0.1

### Describe your issue

Before version 3 the menu would be the top most layer. Since version 3 the menu now appears behind my stack of cards. 
EG:
-> Navbar with dropdown, center logo and icon
-> flex (Card with image overlay) x n

I can see the drop-down menu (text) between the spaces in the cards. 
Is there a simple work around?

If you can't see the problem I will attempt to knock up a simple example, the menu is heavily embedded in my code so I will need to create something from scratch.

Thanks.

![example](https://github.com/saadeghi/daisyui/assets/100543221/7e1cbe1f-0627-4bf5-907e-c121d4e2b4ee)

### What browsers are you seeing the problem on?

All browsers

**Comment by saadeghi** [comment] 2023-06-19 06:45
Duplicate of https://github.com/saadeghi/daisyui/issues/1948#issuecomment-1581632158

**Closed by saadeghi** 2023-06-19 06:45 UTC
