### ISSUE TITLE
"RTL" and "LTR" support at runtime

### ISSUE THREAD

**Issue by ibrahimAbdulbasit** [saadeghi/daisyui#1202] opened 2022-10-02 12:55 UTC
hello, first you'r doing great guys. great ui libarary for twcss
i read the docs about RTL support and it shows that we need to use "rtl: true" and put dir='rtl' to root element and the theme will be rtl.
the problem is if i change dir to dir="ltr" things will get broken.. is that mean that daisy ui support "one" dir that should be declared before build time and i cant change it during run time to LTR ?

**Comment by saadeghi** [comment] 2022-10-02 15:56
Duplicate of https://github.com/saadeghi/daisyui/issues/193

Let me know if you have any questions

**Closed by saadeghi** 2022-10-02 15:56 UTC

**Comment by saadeghi** [comment] 2022-12-07 09:49
Having 2 different CSS files for RTL and LTR is the most efficient solution for any CSS library as long as we're using `left` and `right` for paddings, margins, positions, etc. Because they all should be reversed in a RTL page and if we include both styles in one file, all our users should load unused style to their browsers because users either use RTL or LTR almost for ever. It's not something people switch between regularly.  

Here's and example that creates 2 CSS files for `LTR` and `RTL` it switch CSS files using `Alpine.js`.
This example is made a year ago and dependencies are old but you get the idea:  
https://github.com/saadeghi/daisyui-bidirectional-builds

Let me know if you have any questions.
